/*
 * This file is generated by jOOQ.
 */
package com.dataciders.qlivetest.domain.tables.records;


import com.dataciders.qlivetest.domain.tables.AppFieldLayout;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "app_field_layout",
    schema = "public"
)
public class AppFieldLayoutRecord extends UpdatableRecordImpl<AppFieldLayoutRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.app_field_layout.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.app_field_layout.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.app_field_layout.entity_type</code>.
     */
    public void setEntityType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.app_field_layout.entity_type</code>.
     */
    @Column(name = "entity_type", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getEntityType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.app_field_layout.fields</code>.
     */
    public void setFields(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.app_field_layout.fields</code>.
     */
    @Column(name = "fields", nullable = false)
    @NotNull
    public String getFields() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.app_field_layout.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.app_field_layout.created</code>.
     */
    @Column(name = "created", nullable = false, precision = 6)
    @NotNull
    public Timestamp getCreated() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppFieldLayoutRecord
     */
    public AppFieldLayoutRecord() {
        super(AppFieldLayout.APP_FIELD_LAYOUT);
    }

    /**
     * Create a detached, initialised AppFieldLayoutRecord
     */
    public AppFieldLayoutRecord(String id, String entityType, String fields, Timestamp created) {
        super(AppFieldLayout.APP_FIELD_LAYOUT);

        setId(id);
        setEntityType(entityType);
        setFields(fields);
        setCreated(created);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AppFieldLayoutRecord
     */
    public AppFieldLayoutRecord(com.dataciders.qlivetest.domain.tables.pojos.AppFieldLayout value) {
        super(AppFieldLayout.APP_FIELD_LAYOUT);

        if (value != null) {
            setId(value.getId());
            setEntityType(value.getEntityType());
            setFields(value.getFields());
            setCreated(value.getCreated());
            resetChangedOnNotNull();
        }
    }
}
