/*
 * This file is generated by jOOQ.
 */
package com.dataciders.qlivetest.domain.tables.records;


import com.dataciders.qlivetest.domain.tables.AppUser;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "app_user",
    schema = "public",
    uniqueConstraints = {
        @UniqueConstraint(name = "uc_app_user_login", columnNames = { "login" })
    }
)
public class AppUserRecord extends UpdatableRecordImpl<AppUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.app_user.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.app_user.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.app_user.login</code>.
     */
    public void setLogin(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.app_user.login</code>.
     */
    @Column(name = "login", nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    public String getLogin() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.app_user.password</code>.
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.app_user.password</code>.
     */
    @Column(name = "password", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.app_user.disabled</code>.
     */
    public void setDisabled(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.app_user.disabled</code>.
     */
    @Column(name = "disabled")
    public Boolean getDisabled() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.app_user.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.app_user.created</code>.
     */
    @Column(name = "created", nullable = false, precision = 6)
    @NotNull
    public Timestamp getCreated() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.app_user.last_login</code>.
     */
    public void setLastLogin(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.app_user.last_login</code>.
     */
    @Column(name = "last_login", precision = 6)
    public Timestamp getLastLogin() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.app_user.roles</code>.
     */
    public void setRoles(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.app_user.roles</code>.
     */
    @Column(name = "roles", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    public String getRoles() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppUserRecord
     */
    public AppUserRecord() {
        super(AppUser.APP_USER);
    }

    /**
     * Create a detached, initialised AppUserRecord
     */
    public AppUserRecord(String id, String login, String password, Boolean disabled, Timestamp created, Timestamp lastLogin, String roles) {
        super(AppUser.APP_USER);

        setId(id);
        setLogin(login);
        setPassword(password);
        setDisabled(disabled);
        setCreated(created);
        setLastLogin(lastLogin);
        setRoles(roles);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AppUserRecord
     */
    public AppUserRecord(com.dataciders.qlivetest.domain.tables.pojos.AppUser value) {
        super(AppUser.APP_USER);

        if (value != null) {
            setId(value.getId());
            setLogin(value.getLogin());
            setPassword(value.getPassword());
            setDisabled(value.getDisabled());
            setCreated(value.getCreated());
            setLastLogin(value.getLastLogin());
            setRoles(value.getRoles());
            resetChangedOnNotNull();
        }
    }
}
