/*
 * This file is generated by jOOQ.
 */
package com.dataciders.qlivetest.domain.tables.records;


import com.dataciders.qlivetest.domain.tables.AppVersion;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.math.BigInteger;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "app_version",
    schema = "public"
)
public class AppVersionRecord extends UpdatableRecordImpl<AppVersionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.app_version.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.app_version.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.app_version.field_mask</code>.
     */
    public void setFieldMask(BigInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.app_version.field_mask</code>.
     */
    @Column(name = "field_mask", nullable = false, precision = 39)
    @NotNull
    public BigInteger getFieldMask() {
        return (BigInteger) get(1);
    }

    /**
     * Setter for <code>public.app_version.owner_id</code>.
     */
    public void setOwnerId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.app_version.owner_id</code>.
     */
    @Column(name = "owner_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getOwnerId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.app_version.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.app_version.created</code>.
     */
    @Column(name = "created", nullable = false, precision = 6)
    @NotNull
    public Timestamp getCreated() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>public.app_version.entity_type</code>.
     */
    public void setEntityType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.app_version.entity_type</code>.
     */
    @Column(name = "entity_type", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getEntityType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.app_version.entity_id</code>.
     */
    public void setEntityId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.app_version.entity_id</code>.
     */
    @Column(name = "entity_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getEntityId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.app_version.prev</code>.
     */
    public void setPrev(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.app_version.prev</code>.
     */
    @Column(name = "prev", length = 36)
    @Size(max = 36)
    public String getPrev() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.app_version.field_layout</code>.
     */
    public void setFieldLayout(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.app_version.field_layout</code>.
     */
    @Column(name = "field_layout", nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    public String getFieldLayout() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppVersionRecord
     */
    public AppVersionRecord() {
        super(AppVersion.APP_VERSION);
    }

    /**
     * Create a detached, initialised AppVersionRecord
     */
    public AppVersionRecord(String id, BigInteger fieldMask, String ownerId, Timestamp created, String entityType, String entityId, String prev, String fieldLayout) {
        super(AppVersion.APP_VERSION);

        setId(id);
        setFieldMask(fieldMask);
        setOwnerId(ownerId);
        setCreated(created);
        setEntityType(entityType);
        setEntityId(entityId);
        setPrev(prev);
        setFieldLayout(fieldLayout);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AppVersionRecord
     */
    public AppVersionRecord(com.dataciders.qlivetest.domain.tables.pojos.AppVersion value) {
        super(AppVersion.APP_VERSION);

        if (value != null) {
            setId(value.getId());
            setFieldMask(value.getFieldMask());
            setOwnerId(value.getOwnerId());
            setCreated(value.getCreated());
            setEntityType(value.getEntityType());
            setEntityId(value.getEntityId());
            setPrev(value.getPrev());
            setFieldLayout(value.getFieldLayout());
            resetChangedOnNotNull();
        }
    }
}
