/*
 * This file is generated by jOOQ.
 */
package com.dataciders.qlivetest.domain.tables.records;


import com.dataciders.qlivetest.domain.tables.BarLink;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "bar_link",
    schema = "public",
    uniqueConstraints = {
        @UniqueConstraint(name = "uc_bar_link_bar_baz", columnNames = { "bar_id", "baz_id" })
    }
)
public class BarLinkRecord extends UpdatableRecordImpl<BarLinkRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.bar_link.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.bar_link.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.bar_link.bar_id</code>.
     */
    public void setBarId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.bar_link.bar_id</code>.
     */
    @Column(name = "bar_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getBarId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.bar_link.baz_id</code>.
     */
    public void setBazId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.bar_link.baz_id</code>.
     */
    @Column(name = "baz_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getBazId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.bar_link.version</code>.
     */
    public void setVersion(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.bar_link.version</code>.
     */
    @Column(name = "version", length = 36)
    @Size(max = 36)
    public String getVersion() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BarLinkRecord
     */
    public BarLinkRecord() {
        super(BarLink.BAR_LINK);
    }

    /**
     * Create a detached, initialised BarLinkRecord
     */
    public BarLinkRecord(String id, String barId, String bazId, String version) {
        super(BarLink.BAR_LINK);

        setId(id);
        setBarId(barId);
        setBazId(bazId);
        setVersion(version);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised BarLinkRecord
     */
    public BarLinkRecord(com.dataciders.qlivetest.domain.tables.pojos.BarLink value) {
        super(BarLink.BAR_LINK);

        if (value != null) {
            setId(value.getId());
            setBarId(value.getBarId());
            setBazId(value.getBazId());
            setVersion(value.getVersion());
            resetChangedOnNotNull();
        }
    }
}
