/*
 * This file is generated by jOOQ.
 */
package com.dataciders.qlivetest.domain.tables.records;


import com.dataciders.qlivetest.domain.tables.Qux;

import de.quinscape.domainql.jsonb.JSONB;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Every scalar type a column can hold, for exercising the scalar handling end
 * to end
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "qux",
    schema = "public"
)
public class QuxRecord extends UpdatableRecordImpl<QuxRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.qux.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.qux.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.qux.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.qux.name</code>.
     */
    @Column(name = "name", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.qux.bool</code>.
     */
    public void setBool(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.qux.bool</code>.
     */
    @Column(name = "bool")
    public Boolean getBool() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.qux.int_value</code>.
     */
    public void setIntValue(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.qux.int_value</code>.
     */
    @Column(name = "int_value")
    public Integer getIntValue() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.qux.double_value</code>.
     */
    public void setDoubleValue(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.qux.double_value</code>.
     */
    @Column(name = "double_value")
    public Double getDoubleValue() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>public.qux.string_value</code>.
     */
    public void setStringValue(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.qux.string_value</code>.
     */
    @Column(name = "string_value", length = 255)
    @Size(max = 255)
    public String getStringValue() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.qux.timestamp_value</code>.
     */
    public void setTimestampValue(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.qux.timestamp_value</code>.
     */
    @Column(name = "timestamp_value", precision = 6)
    public Timestamp getTimestampValue() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>public.qux.date_value</code>.
     */
    public void setDateValue(Date value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.qux.date_value</code>.
     */
    @Column(name = "date_value")
    public Date getDateValue() {
        return (Date) get(7);
    }

    /**
     * Setter for <code>public.qux.long_value</code>.
     */
    public void setLongValue(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.qux.long_value</code>.
     */
    @Column(name = "long_value")
    public Long getLongValue() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.qux.currency_value</code>.
     */
    public void setCurrencyValue(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.qux.currency_value</code>.
     */
    @Column(name = "currency_value")
    public Long getCurrencyValue() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>public.qux.byte_value</code>.
     */
    public void setByteValue(Byte value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.qux.byte_value</code>.
     */
    @Column(name = "byte_value")
    public Byte getByteValue() {
        return (Byte) get(10);
    }

    /**
     * Setter for <code>public.qux.big_decimal_value</code>.
     */
    public void setBigDecimalValue(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.qux.big_decimal_value</code>.
     */
    @Column(name = "big_decimal_value", precision = 30, scale = 10)
    public BigDecimal getBigDecimalValue() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>public.qux.jsonb_value</code>.
     */
    public void setJsonbValue(JSONB value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.qux.jsonb_value</code>.
     */
    @Column(name = "jsonb_value")
    public JSONB getJsonbValue() {
        return (JSONB) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuxRecord
     */
    public QuxRecord() {
        super(Qux.QUX);
    }

    /**
     * Create a detached, initialised QuxRecord
     */
    public QuxRecord(String id, String name, Boolean bool, Integer intValue, Double doubleValue, String stringValue, Timestamp timestampValue, Date dateValue, Long longValue, Long currencyValue, Byte byteValue, BigDecimal bigDecimalValue, JSONB jsonbValue) {
        super(Qux.QUX);

        setId(id);
        setName(name);
        setBool(bool);
        setIntValue(intValue);
        setDoubleValue(doubleValue);
        setStringValue(stringValue);
        setTimestampValue(timestampValue);
        setDateValue(dateValue);
        setLongValue(longValue);
        setCurrencyValue(currencyValue);
        setByteValue(byteValue);
        setBigDecimalValue(bigDecimalValue);
        setJsonbValue(jsonbValue);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised QuxRecord
     */
    public QuxRecord(com.dataciders.qlivetest.domain.tables.pojos.Qux value) {
        super(Qux.QUX);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setBool(value.getBool());
            setIntValue(value.getIntValue());
            setDoubleValue(value.getDoubleValue());
            setStringValue(value.getStringValue());
            setTimestampValue(value.getTimestampValue());
            setDateValue(value.getDateValue());
            setLongValue(value.getLongValue());
            setCurrencyValue(value.getCurrencyValue());
            setByteValue(value.getByteValue());
            setBigDecimalValue(value.getBigDecimalValue());
            setJsonbValue(value.getJsonbValue());
            resetChangedOnNotNull();
        }
    }
}
