/*
 * This file is generated by jOOQ.
 */
package io.github.qlivedev.graphql.testdomain;


import io.github.qlivedev.graphql.testdomain.tables.Bar;
import io.github.qlivedev.graphql.testdomain.tables.BarOrg;
import io.github.qlivedev.graphql.testdomain.tables.BarOwner;
import io.github.qlivedev.graphql.testdomain.tables.Foo;
import io.github.qlivedev.graphql.testdomain.tables.SourceEight;
import io.github.qlivedev.graphql.testdomain.tables.SourceFive;
import io.github.qlivedev.graphql.testdomain.tables.SourceFour;
import io.github.qlivedev.graphql.testdomain.tables.SourceNine;
import io.github.qlivedev.graphql.testdomain.tables.SourceOne;
import io.github.qlivedev.graphql.testdomain.tables.SourceSeven;
import io.github.qlivedev.graphql.testdomain.tables.SourceSix;
import io.github.qlivedev.graphql.testdomain.tables.SourceThree;
import io.github.qlivedev.graphql.testdomain.tables.SourceTwo;
import io.github.qlivedev.graphql.testdomain.tables.TargetEight;
import io.github.qlivedev.graphql.testdomain.tables.TargetFive;
import io.github.qlivedev.graphql.testdomain.tables.TargetFour;
import io.github.qlivedev.graphql.testdomain.tables.TargetNine;
import io.github.qlivedev.graphql.testdomain.tables.TargetNineCounts;
import io.github.qlivedev.graphql.testdomain.tables.TargetOne;
import io.github.qlivedev.graphql.testdomain.tables.TargetSeven;
import io.github.qlivedev.graphql.testdomain.tables.TargetSix;
import io.github.qlivedev.graphql.testdomain.tables.TargetThree;
import io.github.qlivedev.graphql.testdomain.tables.TargetTwo;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.bar</code>.
     */
    public static final Bar BAR = Bar.BAR;

    /**
     * The table <code>public.bar_org</code>.
     */
    public static final BarOrg BAR_ORG = BarOrg.BAR_ORG;

    /**
     * The table <code>public.bar_owner</code>.
     */
    public static final BarOwner BAR_OWNER = BarOwner.BAR_OWNER;

    /**
     * The table <code>public.foo</code>.
     */
    public static final Foo FOO = Foo.FOO;

    /**
     * The table <code>public.source_eight</code>.
     */
    public static final SourceEight SOURCE_EIGHT = SourceEight.SOURCE_EIGHT;

    /**
     * The table <code>public.source_five</code>.
     */
    public static final SourceFive SOURCE_FIVE = SourceFive.SOURCE_FIVE;

    /**
     * The table <code>public.source_four</code>.
     */
    public static final SourceFour SOURCE_FOUR = SourceFour.SOURCE_FOUR;

    /**
     * The table <code>public.source_nine</code>.
     */
    public static final SourceNine SOURCE_NINE = SourceNine.SOURCE_NINE;

    /**
     * The table <code>public.source_one</code>.
     */
    public static final SourceOne SOURCE_ONE = SourceOne.SOURCE_ONE;

    /**
     * The table <code>public.source_seven</code>.
     */
    public static final SourceSeven SOURCE_SEVEN = SourceSeven.SOURCE_SEVEN;

    /**
     * The table <code>public.source_six</code>.
     */
    public static final SourceSix SOURCE_SIX = SourceSix.SOURCE_SIX;

    /**
     * The table <code>public.source_three</code>.
     */
    public static final SourceThree SOURCE_THREE = SourceThree.SOURCE_THREE;

    /**
     * The table <code>public.source_two</code>.
     */
    public static final SourceTwo SOURCE_TWO = SourceTwo.SOURCE_TWO;

    /**
     * The table <code>public.target_eight</code>.
     */
    public static final TargetEight TARGET_EIGHT = TargetEight.TARGET_EIGHT;

    /**
     * The table <code>public.target_five</code>.
     */
    public static final TargetFive TARGET_FIVE = TargetFive.TARGET_FIVE;

    /**
     * The table <code>public.target_four</code>.
     */
    public static final TargetFour TARGET_FOUR = TargetFour.TARGET_FOUR;

    /**
     * The table <code>public.target_nine</code>.
     */
    public static final TargetNine TARGET_NINE = TargetNine.TARGET_NINE;

    /**
     * The table <code>public.target_nine_counts</code>.
     */
    public static final TargetNineCounts TARGET_NINE_COUNTS = TargetNineCounts.TARGET_NINE_COUNTS;

    /**
     * The table <code>public.target_one</code>.
     */
    public static final TargetOne TARGET_ONE = TargetOne.TARGET_ONE;

    /**
     * The table <code>public.target_seven</code>.
     */
    public static final TargetSeven TARGET_SEVEN = TargetSeven.TARGET_SEVEN;

    /**
     * The table <code>public.target_six</code>.
     */
    public static final TargetSix TARGET_SIX = TargetSix.TARGET_SIX;

    /**
     * The table <code>public.target_three</code>.
     */
    public static final TargetThree TARGET_THREE = TargetThree.TARGET_THREE;

    /**
     * The table <code>public.target_two</code>.
     */
    public static final TargetTwo TARGET_TWO = TargetTwo.TARGET_TWO;
}
