package io.github.qlivedev.model.merge;

import jakarta.validation.constraints.NotNull;

import java.util.List;

/**
 * Everything one row of one type changed by, as a working set hands it over.
 *
 * A change names the row, the base it was read at and the fields that changed -- never the whole row. What
 * the user did not touch is not in here, which is what makes a concurrent change to a different field
 * mergeable rather than a clash.
 */
public class EntityChange
{
    private String type;

    private String id;

    private String version;

    private boolean isNew;

    private List<FieldChange> changes;


    /**
     * GraphQL name of the type whose row this is.
     */
    @NotNull
    public String getType()
    {
        return type;
    }


    public void setType(String type)
    {
        this.type = type;
    }


    /**
     * Id of the row. Generated by the client for a new row, so that changes can refer to each other before
     * the server has seen any of them.
     */
    @NotNull
    public String getId()
    {
        return id;
    }


    public void setId(String id)
    {
        this.id = id;
    }


    /**
     * The version the row was read at, and the whole of the optimistic lock: the write only lands while the
     * stored version is still this one. Null for a new row and for a type that carries no version field.
     */
    public String getVersion()
    {
        return version;
    }


    public void setVersion(String version)
    {
        this.version = version;
    }


    /**
     * true if the row does not exist yet and the change is an insert. The client says so rather than the
     * server guessing: an unversioned type has no version to read the answer off, and a row that was deleted
     * elsewhere must not be silently recreated by an update that found nothing.
     */
    @NotNull
    public boolean isNew()
    {
        return isNew;
    }


    public void setNew(boolean isNew)
    {
        this.isNew = isNew;
    }


    /**
     * The fields that changed, one entry each.
     */
    @NotNull
    public List<FieldChange> getChanges()
    {
        return changes;
    }


    public void setChanges(List<FieldChange> changes)
    {
        this.changes = changes;
    }


    @Override
    public String toString()
    {
        return super.toString() + ": "
            + "type = '" + type + '\''
            + ", id = '" + id + '\''
            + ", version = '" + version + '\''
            + ", isNew = " + isNew
            + ", changes = " + changes
            ;
    }
}
