/*
 * This file is generated by jOOQ.
 */
package io.github.qlivedev.qlivetest.domain.tables.records;


import io.github.qlivedev.qlivetest.domain.tables.AppLogin;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "app_login",
    schema = "public"
)
public class AppLoginRecord extends UpdatableRecordImpl<AppLoginRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.app_login.username</code>.
     */
    public void setUsername(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.app_login.username</code>.
     */
    @Column(name = "username", nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    public String getUsername() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.app_login.series</code>.
     */
    public void setSeries(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.app_login.series</code>.
     */
    @Id
    @Column(name = "series", nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    public String getSeries() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.app_login.token</code>.
     */
    public void setToken(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.app_login.token</code>.
     */
    @Column(name = "token", nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    public String getToken() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.app_login.last_used</code>.
     */
    public void setLastUsed(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.app_login.last_used</code>.
     */
    @Column(name = "last_used", nullable = false, precision = 6)
    @NotNull
    public Timestamp getLastUsed() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppLoginRecord
     */
    public AppLoginRecord() {
        super(AppLogin.APP_LOGIN);
    }

    /**
     * Create a detached, initialised AppLoginRecord
     */
    public AppLoginRecord(String username, String series, String token, Timestamp lastUsed) {
        super(AppLogin.APP_LOGIN);

        setUsername(username);
        setSeries(series);
        setToken(token);
        setLastUsed(lastUsed);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AppLoginRecord
     */
    public AppLoginRecord(io.github.qlivedev.qlivetest.domain.tables.pojos.AppLogin value) {
        super(AppLogin.APP_LOGIN);

        if (value != null) {
            setUsername(value.getUsername());
            setSeries(value.getSeries());
            setToken(value.getToken());
            setLastUsed(value.getLastUsed());
            resetChangedOnNotNull();
        }
    }
}
