/*
 * This file is generated by jOOQ.
 */
package io.github.qlivedev.qlivetest.domain.tables.records;


import io.github.qlivedev.qlivetest.domain.tables.Quux;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "quux",
    schema = "public"
)
public class QuuxRecord extends UpdatableRecordImpl<QuuxRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.quux.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.quux.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.quux.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.quux.name</code>.
     */
    @Column(name = "name", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.quux.num_a</code>.
     */
    public void setNumA(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.quux.num_a</code>.
     */
    @Column(name = "num_a", nullable = false)
    @NotNull
    public Integer getNumA() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.quux.num_b</code>.
     */
    public void setNumB(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.quux.num_b</code>.
     */
    @Column(name = "num_b", nullable = false)
    @NotNull
    public Integer getNumB() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.quux.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.quux.created</code>.
     */
    @Column(name = "created", nullable = false, precision = 6)
    @NotNull
    public Timestamp getCreated() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuuxRecord
     */
    public QuuxRecord() {
        super(Quux.QUUX);
    }

    /**
     * Create a detached, initialised QuuxRecord
     */
    public QuuxRecord(String id, String name, Integer numA, Integer numB, Timestamp created) {
        super(Quux.QUUX);

        setId(id);
        setName(name);
        setNumA(numA);
        setNumB(numB);
        setCreated(created);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised QuuxRecord
     */
    public QuuxRecord(io.github.qlivedev.qlivetest.domain.tables.pojos.Quux value) {
        super(Quux.QUUX);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setNumA(value.getNumA());
            setNumB(value.getNumB());
            setCreated(value.getCreated());
            resetChangedOnNotNull();
        }
    }
}
