/*
 * This file is generated by jOOQ.
 */
package io.github.qlivedev.qlivetest.domain.tables;


import io.github.qlivedev.qlivetest.domain.Keys;
import io.github.qlivedev.qlivetest.domain.Public;
import io.github.qlivedev.qlivetest.domain.tables.records.AppLoginRecord;

import java.sql.Timestamp;
import java.util.Collection;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AppLogin extends TableImpl<AppLoginRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.app_login</code>
     */
    public static final AppLogin APP_LOGIN = new AppLogin();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppLoginRecord> getRecordType() {
        return AppLoginRecord.class;
    }

    /**
     * The column <code>public.app_login.username</code>.
     */
    public final TableField<AppLoginRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.app_login.series</code>.
     */
    public final TableField<AppLoginRecord, String> SERIES = createField(DSL.name("series"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.app_login.token</code>.
     */
    public final TableField<AppLoginRecord, String> TOKEN = createField(DSL.name("token"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.app_login.last_used</code>.
     */
    public final TableField<AppLoginRecord, Timestamp> LAST_USED = createField(DSL.name("last_used"), SQLDataType.TIMESTAMP(6).nullable(false), this, "");

    private AppLogin(Name alias, Table<AppLoginRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AppLogin(Name alias, Table<AppLoginRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.app_login</code> table reference
     */
    public AppLogin(String alias) {
        this(DSL.name(alias), APP_LOGIN);
    }

    /**
     * Create an aliased <code>public.app_login</code> table reference
     */
    public AppLogin(Name alias) {
        this(alias, APP_LOGIN);
    }

    /**
     * Create a <code>public.app_login</code> table reference
     */
    public AppLogin() {
        this(DSL.name("app_login"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AppLoginRecord> getPrimaryKey() {
        return Keys.PK_APP_LOGIN;
    }

    @Override
    public AppLogin as(String alias) {
        return new AppLogin(DSL.name(alias), this);
    }

    @Override
    public AppLogin as(Name alias) {
        return new AppLogin(alias, this);
    }

    @Override
    public AppLogin as(Table<?> alias) {
        return new AppLogin(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AppLogin rename(String name) {
        return new AppLogin(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppLogin rename(Name name) {
        return new AppLogin(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppLogin rename(Table<?> name) {
        return new AppLogin(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppLogin where(Condition condition) {
        return new AppLogin(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppLogin where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppLogin where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppLogin where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppLogin where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppLogin where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppLogin where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppLogin where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppLogin whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppLogin whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
