/*
 * This file is generated by jOOQ.
 */
package io.github.qlivedev.qlivetest.domain.tables;


import io.github.qlivedev.qlivetest.domain.Keys;
import io.github.qlivedev.qlivetest.domain.Public;
import io.github.qlivedev.qlivetest.domain.tables.Foo.FooPath;
import io.github.qlivedev.qlivetest.domain.tables.records.FooTypeRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FooType extends TableImpl<FooTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.foo_type</code>
     */
    public static final FooType FOO_TYPE = new FooType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FooTypeRecord> getRecordType() {
        return FooTypeRecord.class;
    }

    /**
     * The column <code>public.foo_type.ordinal</code>.
     */
    public final TableField<FooTypeRecord, Integer> ORDINAL = createField(DSL.name("ordinal"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.foo_type.name</code>.
     */
    public final TableField<FooTypeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private FooType(Name alias, Table<FooTypeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FooType(Name alias, Table<FooTypeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.foo_type</code> table reference
     */
    public FooType(String alias) {
        this(DSL.name(alias), FOO_TYPE);
    }

    /**
     * Create an aliased <code>public.foo_type</code> table reference
     */
    public FooType(Name alias) {
        this(alias, FOO_TYPE);
    }

    /**
     * Create a <code>public.foo_type</code> table reference
     */
    public FooType() {
        this(DSL.name("foo_type"), null);
    }

    public <O extends Record> FooType(Table<O> path, ForeignKey<O, FooTypeRecord> childPath, InverseForeignKey<O, FooTypeRecord> parentPath) {
        super(path, childPath, parentPath, FOO_TYPE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.30"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class FooTypePath extends FooType implements Path<FooTypeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> FooTypePath(Table<O> path, ForeignKey<O, FooTypeRecord> childPath, InverseForeignKey<O, FooTypeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private FooTypePath(Name alias, Table<FooTypeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public FooTypePath as(String alias) {
            return new FooTypePath(DSL.name(alias), this);
        }

        @Override
        public FooTypePath as(Name alias) {
            return new FooTypePath(alias, this);
        }

        @Override
        public FooTypePath as(Table<?> alias) {
            return new FooTypePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<FooTypeRecord> getPrimaryKey() {
        return Keys.PK_FOO_TYPE;
    }

    @Override
    public List<UniqueKey<FooTypeRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.FOO_TYPE_NAME_KEY);
    }

    private transient FooPath _foo;

    /**
     * Get the implicit to-many join path to the <code>public.foo</code> table
     */
    public FooPath foo() {
        if (_foo == null)
            _foo = new FooPath(this, null, Keys.FOO__FK_FOO_TYPE_ID.getInverseKey());

        return _foo;
    }

    @Override
    public FooType as(String alias) {
        return new FooType(DSL.name(alias), this);
    }

    @Override
    public FooType as(Name alias) {
        return new FooType(alias, this);
    }

    @Override
    public FooType as(Table<?> alias) {
        return new FooType(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FooType rename(String name) {
        return new FooType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FooType rename(Name name) {
        return new FooType(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FooType rename(Table<?> name) {
        return new FooType(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FooType where(Condition condition) {
        return new FooType(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FooType where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FooType where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FooType where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FooType where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FooType where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FooType where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FooType where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FooType whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FooType whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
