/*
 * This file is generated by jOOQ.
 */
package io.github.qlivedev.qlivetest.domain.tables;


import io.github.qlivedev.graphql.jsonb.JSONB;
import io.github.qlivedev.graphql.jsonb.PGJSONBinding;
import io.github.qlivedev.qlivetest.domain.Keys;
import io.github.qlivedev.qlivetest.domain.Public;
import io.github.qlivedev.qlivetest.domain.tables.records.QuxRecord;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.Collection;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Every scalar type a column can hold, for exercising the scalar handling end
 * to end
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Qux extends TableImpl<QuxRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.qux</code>
     */
    public static final Qux QUX = new Qux();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QuxRecord> getRecordType() {
        return QuxRecord.class;
    }

    /**
     * The column <code>public.qux.id</code>.
     */
    public final TableField<QuxRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.qux.name</code>.
     */
    public final TableField<QuxRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.qux.bool</code>.
     */
    public final TableField<QuxRecord, Boolean> BOOL = createField(DSL.name("bool"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.qux.int_value</code>.
     */
    public final TableField<QuxRecord, Integer> INT_VALUE = createField(DSL.name("int_value"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.qux.double_value</code>.
     */
    public final TableField<QuxRecord, Double> DOUBLE_VALUE = createField(DSL.name("double_value"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.qux.string_value</code>.
     */
    public final TableField<QuxRecord, String> STRING_VALUE = createField(DSL.name("string_value"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.qux.timestamp_value</code>.
     */
    public final TableField<QuxRecord, Timestamp> TIMESTAMP_VALUE = createField(DSL.name("timestamp_value"), SQLDataType.TIMESTAMP(6), this, "");

    /**
     * The column <code>public.qux.date_value</code>.
     */
    public final TableField<QuxRecord, Date> DATE_VALUE = createField(DSL.name("date_value"), SQLDataType.DATE, this, "");

    /**
     * The column <code>public.qux.long_value</code>.
     */
    public final TableField<QuxRecord, Long> LONG_VALUE = createField(DSL.name("long_value"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.qux.currency_value</code>.
     */
    public final TableField<QuxRecord, Long> CURRENCY_VALUE = createField(DSL.name("currency_value"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.qux.byte_value</code>.
     */
    public final TableField<QuxRecord, Byte> BYTE_VALUE = createField(DSL.name("byte_value"), SQLDataType.TINYINT, this, "");

    /**
     * The column <code>public.qux.big_decimal_value</code>.
     */
    public final TableField<QuxRecord, BigDecimal> BIG_DECIMAL_VALUE = createField(DSL.name("big_decimal_value"), SQLDataType.NUMERIC(30, 10), this, "");

    /**
     * The column <code>public.qux.jsonb_value</code>.
     */
    public final TableField<QuxRecord, JSONB> JSONB_VALUE = createField(DSL.name("jsonb_value"), SQLDataType.JSONB, this, "", new PGJSONBinding());

    private Qux(Name alias, Table<QuxRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Qux(Name alias, Table<QuxRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Every scalar type a column can hold, for exercising the scalar handling end to end"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.qux</code> table reference
     */
    public Qux(String alias) {
        this(DSL.name(alias), QUX);
    }

    /**
     * Create an aliased <code>public.qux</code> table reference
     */
    public Qux(Name alias) {
        this(alias, QUX);
    }

    /**
     * Create a <code>public.qux</code> table reference
     */
    public Qux() {
        this(DSL.name("qux"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<QuxRecord> getPrimaryKey() {
        return Keys.PK_QUX;
    }

    @Override
    public Qux as(String alias) {
        return new Qux(DSL.name(alias), this);
    }

    @Override
    public Qux as(Name alias) {
        return new Qux(alias, this);
    }

    @Override
    public Qux as(Table<?> alias) {
        return new Qux(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Qux rename(String name) {
        return new Qux(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Qux rename(Name name) {
        return new Qux(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Qux rename(Table<?> name) {
        return new Qux(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Qux where(Condition condition) {
        return new Qux(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Qux where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Qux where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Qux where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Qux where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Qux where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Qux where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Qux where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Qux whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Qux whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
