/*
 * This file is generated by jOOQ.
 */
package com.dataciders.qlive.testdomain.tables.records;


import com.dataciders.qlive.testdomain.tables.pojos.TestFoo;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "test_foo",
    schema = "public"
)
public class TestFooRecord extends UpdatableRecordImpl<TestFooRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.test_foo.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.test_foo.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.test_foo.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.test_foo.name</code>.
     */
    @Column(name = "name", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.test_foo.num</code>.
     */
    public void setNum(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.test_foo.num</code>.
     */
    @Column(name = "num", nullable = false)
    @NotNull
    public Integer getNum() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.test_foo.type</code>.
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.test_foo.type</code>.
     */
    @Column(name = "type", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.test_foo.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.test_foo.created</code>.
     */
    @Column(name = "created", nullable = false, precision = 6)
    @NotNull
    public Timestamp getCreated() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.test_foo.description</code>.
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.test_foo.description</code>.
     */
    @Column(name = "description")
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.test_foo.owner_id</code>.
     */
    public void setOwnerId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.test_foo.owner_id</code>.
     */
    @Column(name = "owner_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getOwnerId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.test_foo.flag</code>.
     */
    public void setFlag(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.test_foo.flag</code>.
     */
    @Column(name = "flag", nullable = false)
    @NotNull
    public Boolean getFlag() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.test_foo.version</code>.
     */
    public void setVersion(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.test_foo.version</code>.
     */
    @Column(name = "version", length = 36)
    @Size(max = 36)
    public String getVersion() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TestFooRecord
     */
    public TestFooRecord() {
        super(com.dataciders.qlive.testdomain.tables.TestFoo.TEST_FOO);
    }

    /**
     * Create a detached, initialised TestFooRecord
     */
    public TestFooRecord(String id, String name, Integer num, String type, Timestamp created, String description, String ownerId, Boolean flag, String version) {
        super(com.dataciders.qlive.testdomain.tables.TestFoo.TEST_FOO);

        setId(id);
        setName(name);
        setNum(num);
        setType(type);
        setCreated(created);
        setDescription(description);
        setOwnerId(ownerId);
        setFlag(flag);
        setVersion(version);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TestFooRecord
     */
    public TestFooRecord(TestFoo value) {
        super(com.dataciders.qlive.testdomain.tables.TestFoo.TEST_FOO);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setNum(value.getNum());
            setType(value.getType());
            setCreated(value.getCreated());
            setDescription(value.getDescription());
            setOwnerId(value.getOwnerId());
            setFlag(value.getFlag());
            setVersion(value.getVersion());
            resetChangedOnNotNull();
        }
    }
}
