spring.datasource.url=jdbc:postgresql://localhost:5432/qlivetest
spring.datasource.username=qlivetest
spring.datasource.password=qlivetest
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true

application.remember-me.key=a194bd1e-f653-4468-b7b3-23f1733726a4


logging.level.org.springframework.security=DEBUG
logging.level.org.jooq.tools.LoggerListener=DEBUG

#logging.level.io.github.qlivedev.runtime.controller.TrackUsageDevController=DEBUG
logging.level.io.github.qlivedev.runtime.pubsub.DefaultPubSubService=DEBUG

