spring.application.name=QLive Test
spring.profiles.default=dev

server.port=8080

logging.level.org.springframework.security=DEBUG

logging.level.com.dataciders.qlive.runtime.domain.GraphQLQueryTypingService=DEBUG
logging.level.com.dataciders.qlive.runtime.query.QueryPlanBuilder=DEBUG
logging.level.com.dataciders.qlive.runtime.controller.TrackUsageDevController=DEBUG
