spring.application.name=QLive Test
server.port=8080

logging.level.org.springframework.security=DEBUG

logging.level.com.dataciders.qlive.runtime.domain.GraphQLQueryTypingService=DEBUG
logging.level.com.dataciders.qlive.runtime.query.QueryPlanBuilder=DEBUG
