/*
 * This file is generated by jOOQ.
 */
package com.dataciders.qlive.testdomain;


import com.dataciders.qlive.testdomain.tables.TestFoo;
import com.dataciders.qlive.testdomain.tables.TestFooType;
import com.dataciders.qlive.testdomain.tables.TestUser;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.test_foo</code>.
     */
    public static final TestFoo TEST_FOO = TestFoo.TEST_FOO;

    /**
     * The table <code>public.test_foo_type</code>.
     */
    public static final TestFooType TEST_FOO_TYPE = TestFooType.TEST_FOO_TYPE;

    /**
     * The table <code>public.test_user</code>.
     */
    public static final TestUser TEST_USER = TestUser.TEST_USER;
}
