/*
 * This file is generated by jOOQ.
 */
package io.github.qlivedev.testdomain.tables.records;


import io.github.qlivedev.testdomain.tables.pojos.TestFooType;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "test_foo_type",
    schema = "public",
    uniqueConstraints = {
        @UniqueConstraint(name = "test_foo_type_name_key", columnNames = { "name" })
    }
)
public class TestFooTypeRecord extends UpdatableRecordImpl<TestFooTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.test_foo_type.ordinal</code>.
     */
    public void setOrdinal(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.test_foo_type.ordinal</code>.
     */
    @Id
    @Column(name = "ordinal", nullable = false)
    @NotNull
    public Integer getOrdinal() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.test_foo_type.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.test_foo_type.name</code>.
     */
    @Column(name = "name", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TestFooTypeRecord
     */
    public TestFooTypeRecord() {
        super(io.github.qlivedev.testdomain.tables.TestFooType.TEST_FOO_TYPE);
    }

    /**
     * Create a detached, initialised TestFooTypeRecord
     */
    public TestFooTypeRecord(Integer ordinal, String name) {
        super(io.github.qlivedev.testdomain.tables.TestFooType.TEST_FOO_TYPE);

        setOrdinal(ordinal);
        setName(name);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TestFooTypeRecord
     */
    public TestFooTypeRecord(TestFooType value) {
        super(io.github.qlivedev.testdomain.tables.TestFooType.TEST_FOO_TYPE);

        if (value != null) {
            setOrdinal(value.getOrdinal());
            setName(value.getName());
            resetChangedOnNotNull();
        }
    }
}
