/*
 * This file is generated by jOOQ.
 */
package io.github.qlivedev.testdomain;


import io.github.qlivedev.testdomain.tables.TestBar;
import io.github.qlivedev.testdomain.tables.TestBarLink;
import io.github.qlivedev.testdomain.tables.TestBaz;
import io.github.qlivedev.testdomain.tables.TestFoo;
import io.github.qlivedev.testdomain.tables.TestFooType;
import io.github.qlivedev.testdomain.tables.TestUser;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.test_bar</code>.
     */
    public final TestBar TEST_BAR = TestBar.TEST_BAR;

    /**
     * The table <code>public.test_bar_link</code>.
     */
    public final TestBarLink TEST_BAR_LINK = TestBarLink.TEST_BAR_LINK;

    /**
     * The table <code>public.test_baz</code>.
     */
    public final TestBaz TEST_BAZ = TestBaz.TEST_BAZ;

    /**
     * The table <code>public.test_foo</code>.
     */
    public final TestFoo TEST_FOO = TestFoo.TEST_FOO;

    /**
     * The table <code>public.test_foo_type</code>.
     */
    public final TestFooType TEST_FOO_TYPE = TestFooType.TEST_FOO_TYPE;

    /**
     * The table <code>public.test_user</code>.
     */
    public final TestUser TEST_USER = TestUser.TEST_USER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            TestBar.TEST_BAR,
            TestBarLink.TEST_BAR_LINK,
            TestBaz.TEST_BAZ,
            TestFoo.TEST_FOO,
            TestFooType.TEST_FOO_TYPE,
            TestUser.TEST_USER
        );
    }
}
