/*
 * This file is generated by jOOQ.
 */
package io.github.qlivedev.testdomain;


import io.github.qlivedev.testdomain.tables.TestBar;
import io.github.qlivedev.testdomain.tables.TestBarLink;
import io.github.qlivedev.testdomain.tables.TestBaz;
import io.github.qlivedev.testdomain.tables.TestFoo;
import io.github.qlivedev.testdomain.tables.TestFooType;
import io.github.qlivedev.testdomain.tables.TestUser;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.test_bar</code>.
     */
    public static final TestBar TEST_BAR = TestBar.TEST_BAR;

    /**
     * The table <code>public.test_bar_link</code>.
     */
    public static final TestBarLink TEST_BAR_LINK = TestBarLink.TEST_BAR_LINK;

    /**
     * The table <code>public.test_baz</code>.
     */
    public static final TestBaz TEST_BAZ = TestBaz.TEST_BAZ;

    /**
     * The table <code>public.test_foo</code>.
     */
    public static final TestFoo TEST_FOO = TestFoo.TEST_FOO;

    /**
     * The table <code>public.test_foo_type</code>.
     */
    public static final TestFooType TEST_FOO_TYPE = TestFooType.TEST_FOO_TYPE;

    /**
     * The table <code>public.test_user</code>.
     */
    public static final TestUser TEST_USER = TestUser.TEST_USER;
}
