/*
 * This file is generated by jOOQ.
 */
package io.github.qlivedev.testdomain.tables;


import io.github.qlivedev.testdomain.Keys;
import io.github.qlivedev.testdomain.Public;
import io.github.qlivedev.testdomain.tables.TestBarLink.TestBarLinkPath;
import io.github.qlivedev.testdomain.tables.TestBaz.TestBazPath;
import io.github.qlivedev.testdomain.tables.records.TestBarRecord;

import java.sql.Timestamp;
import java.util.Collection;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TestBar extends TableImpl<TestBarRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.test_bar</code>
     */
    public static final TestBar TEST_BAR = new TestBar();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TestBarRecord> getRecordType() {
        return TestBarRecord.class;
    }

    /**
     * The column <code>public.test_bar.id</code>.
     */
    public final TableField<TestBarRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.test_bar.name</code>.
     */
    public final TableField<TestBarRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.test_bar.num</code>.
     */
    public final TableField<TestBarRecord, Integer> NUM = createField(DSL.name("num"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.test_bar.created</code>.
     */
    public final TableField<TestBarRecord, Timestamp> CREATED = createField(DSL.name("created"), SQLDataType.TIMESTAMP(6).nullable(false), this, "");

    /**
     * The column <code>public.test_bar.description</code>.
     */
    public final TableField<TestBarRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.test_bar.version</code>.
     */
    public final TableField<TestBarRecord, String> VERSION = createField(DSL.name("version"), SQLDataType.VARCHAR(36), this, "");

    private TestBar(Name alias, Table<TestBarRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TestBar(Name alias, Table<TestBarRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.test_bar</code> table reference
     */
    public TestBar(String alias) {
        this(DSL.name(alias), TEST_BAR);
    }

    /**
     * Create an aliased <code>public.test_bar</code> table reference
     */
    public TestBar(Name alias) {
        this(alias, TEST_BAR);
    }

    /**
     * Create a <code>public.test_bar</code> table reference
     */
    public TestBar() {
        this(DSL.name("test_bar"), null);
    }

    public <O extends Record> TestBar(Table<O> path, ForeignKey<O, TestBarRecord> childPath, InverseForeignKey<O, TestBarRecord> parentPath) {
        super(path, childPath, parentPath, TEST_BAR);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.30"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class TestBarPath extends TestBar implements Path<TestBarRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TestBarPath(Table<O> path, ForeignKey<O, TestBarRecord> childPath, InverseForeignKey<O, TestBarRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TestBarPath(Name alias, Table<TestBarRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TestBarPath as(String alias) {
            return new TestBarPath(DSL.name(alias), this);
        }

        @Override
        public TestBarPath as(Name alias) {
            return new TestBarPath(alias, this);
        }

        @Override
        public TestBarPath as(Table<?> alias) {
            return new TestBarPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TestBarRecord> getPrimaryKey() {
        return Keys.PK_TEST_BAR;
    }

    private transient TestBarLinkPath _testBarLink;

    /**
     * Get the implicit to-many join path to the
     * <code>public.test_bar_link</code> table
     */
    public TestBarLinkPath testBarLink() {
        if (_testBarLink == null)
            _testBarLink = new TestBarLinkPath(this, null, Keys.TEST_BAR_LINK__FK_TEST_BAR_LINK_TO_BAR.getInverseKey());

        return _testBarLink;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.test_baz</code> table
     */
    public TestBazPath testBaz() {
        return testBarLink().testBaz();
    }

    @Override
    public TestBar as(String alias) {
        return new TestBar(DSL.name(alias), this);
    }

    @Override
    public TestBar as(Name alias) {
        return new TestBar(alias, this);
    }

    @Override
    public TestBar as(Table<?> alias) {
        return new TestBar(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TestBar rename(String name) {
        return new TestBar(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TestBar rename(Name name) {
        return new TestBar(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TestBar rename(Table<?> name) {
        return new TestBar(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestBar where(Condition condition) {
        return new TestBar(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestBar where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestBar where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestBar where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestBar where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestBar where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestBar where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestBar where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestBar whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestBar whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
