/*
 * This file is generated by jOOQ.
 */
package io.github.qlivedev.testdomain.tables;


import io.github.qlivedev.testdomain.Keys;
import io.github.qlivedev.testdomain.Public;
import io.github.qlivedev.testdomain.tables.TestBar.TestBarPath;
import io.github.qlivedev.testdomain.tables.TestBaz.TestBazPath;
import io.github.qlivedev.testdomain.tables.records.TestBarLinkRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TestBarLink extends TableImpl<TestBarLinkRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.test_bar_link</code>
     */
    public static final TestBarLink TEST_BAR_LINK = new TestBarLink();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TestBarLinkRecord> getRecordType() {
        return TestBarLinkRecord.class;
    }

    /**
     * The column <code>public.test_bar_link.id</code>.
     */
    public final TableField<TestBarLinkRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.test_bar_link.bar_id</code>.
     */
    public final TableField<TestBarLinkRecord, String> BAR_ID = createField(DSL.name("bar_id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.test_bar_link.baz_id</code>.
     */
    public final TableField<TestBarLinkRecord, String> BAZ_ID = createField(DSL.name("baz_id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.test_bar_link.version</code>.
     */
    public final TableField<TestBarLinkRecord, String> VERSION = createField(DSL.name("version"), SQLDataType.VARCHAR(36), this, "");

    private TestBarLink(Name alias, Table<TestBarLinkRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TestBarLink(Name alias, Table<TestBarLinkRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.test_bar_link</code> table reference
     */
    public TestBarLink(String alias) {
        this(DSL.name(alias), TEST_BAR_LINK);
    }

    /**
     * Create an aliased <code>public.test_bar_link</code> table reference
     */
    public TestBarLink(Name alias) {
        this(alias, TEST_BAR_LINK);
    }

    /**
     * Create a <code>public.test_bar_link</code> table reference
     */
    public TestBarLink() {
        this(DSL.name("test_bar_link"), null);
    }

    public <O extends Record> TestBarLink(Table<O> path, ForeignKey<O, TestBarLinkRecord> childPath, InverseForeignKey<O, TestBarLinkRecord> parentPath) {
        super(path, childPath, parentPath, TEST_BAR_LINK);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.30"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class TestBarLinkPath extends TestBarLink implements Path<TestBarLinkRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TestBarLinkPath(Table<O> path, ForeignKey<O, TestBarLinkRecord> childPath, InverseForeignKey<O, TestBarLinkRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TestBarLinkPath(Name alias, Table<TestBarLinkRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TestBarLinkPath as(String alias) {
            return new TestBarLinkPath(DSL.name(alias), this);
        }

        @Override
        public TestBarLinkPath as(Name alias) {
            return new TestBarLinkPath(alias, this);
        }

        @Override
        public TestBarLinkPath as(Table<?> alias) {
            return new TestBarLinkPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TestBarLinkRecord> getPrimaryKey() {
        return Keys.PK_TEST_BAR_LINK;
    }

    @Override
    public List<UniqueKey<TestBarLinkRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UC_TEST_BAR_LINK_BAR_BAZ);
    }

    @Override
    public List<ForeignKey<TestBarLinkRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TEST_BAR_LINK__FK_TEST_BAR_LINK_TO_BAR, Keys.TEST_BAR_LINK__FK_TEST_BAR_LINK_TO_BAZ);
    }

    private transient TestBarPath _testBar;

    /**
     * Get the implicit join path to the <code>public.test_bar</code> table.
     */
    public TestBarPath testBar() {
        if (_testBar == null)
            _testBar = new TestBarPath(this, Keys.TEST_BAR_LINK__FK_TEST_BAR_LINK_TO_BAR, null);

        return _testBar;
    }

    private transient TestBazPath _testBaz;

    /**
     * Get the implicit join path to the <code>public.test_baz</code> table.
     */
    public TestBazPath testBaz() {
        if (_testBaz == null)
            _testBaz = new TestBazPath(this, Keys.TEST_BAR_LINK__FK_TEST_BAR_LINK_TO_BAZ, null);

        return _testBaz;
    }

    @Override
    public TestBarLink as(String alias) {
        return new TestBarLink(DSL.name(alias), this);
    }

    @Override
    public TestBarLink as(Name alias) {
        return new TestBarLink(alias, this);
    }

    @Override
    public TestBarLink as(Table<?> alias) {
        return new TestBarLink(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TestBarLink rename(String name) {
        return new TestBarLink(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TestBarLink rename(Name name) {
        return new TestBarLink(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TestBarLink rename(Table<?> name) {
        return new TestBarLink(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestBarLink where(Condition condition) {
        return new TestBarLink(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestBarLink where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestBarLink where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestBarLink where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestBarLink where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestBarLink where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestBarLink where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestBarLink where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestBarLink whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestBarLink whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
