/*
 * This file is generated by jOOQ.
 */
package io.github.qlivedev.testdomain.tables;


import io.github.qlivedev.testdomain.Keys;
import io.github.qlivedev.testdomain.Public;
import io.github.qlivedev.testdomain.tables.TestBar.TestBarPath;
import io.github.qlivedev.testdomain.tables.TestBarLink.TestBarLinkPath;
import io.github.qlivedev.testdomain.tables.records.TestBazRecord;

import java.sql.Timestamp;
import java.util.Collection;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TestBaz extends TableImpl<TestBazRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.test_baz</code>
     */
    public static final TestBaz TEST_BAZ = new TestBaz();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TestBazRecord> getRecordType() {
        return TestBazRecord.class;
    }

    /**
     * The column <code>public.test_baz.id</code>.
     */
    public final TableField<TestBazRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.test_baz.name</code>.
     */
    public final TableField<TestBazRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.test_baz.num</code>.
     */
    public final TableField<TestBazRecord, Integer> NUM = createField(DSL.name("num"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.test_baz.created</code>.
     */
    public final TableField<TestBazRecord, Timestamp> CREATED = createField(DSL.name("created"), SQLDataType.TIMESTAMP(6).nullable(false), this, "");

    /**
     * The column <code>public.test_baz.description</code>.
     */
    public final TableField<TestBazRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.test_baz.version</code>.
     */
    public final TableField<TestBazRecord, String> VERSION = createField(DSL.name("version"), SQLDataType.VARCHAR(36), this, "");

    private TestBaz(Name alias, Table<TestBazRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TestBaz(Name alias, Table<TestBazRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.test_baz</code> table reference
     */
    public TestBaz(String alias) {
        this(DSL.name(alias), TEST_BAZ);
    }

    /**
     * Create an aliased <code>public.test_baz</code> table reference
     */
    public TestBaz(Name alias) {
        this(alias, TEST_BAZ);
    }

    /**
     * Create a <code>public.test_baz</code> table reference
     */
    public TestBaz() {
        this(DSL.name("test_baz"), null);
    }

    public <O extends Record> TestBaz(Table<O> path, ForeignKey<O, TestBazRecord> childPath, InverseForeignKey<O, TestBazRecord> parentPath) {
        super(path, childPath, parentPath, TEST_BAZ);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.30"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class TestBazPath extends TestBaz implements Path<TestBazRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TestBazPath(Table<O> path, ForeignKey<O, TestBazRecord> childPath, InverseForeignKey<O, TestBazRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TestBazPath(Name alias, Table<TestBazRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TestBazPath as(String alias) {
            return new TestBazPath(DSL.name(alias), this);
        }

        @Override
        public TestBazPath as(Name alias) {
            return new TestBazPath(alias, this);
        }

        @Override
        public TestBazPath as(Table<?> alias) {
            return new TestBazPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TestBazRecord> getPrimaryKey() {
        return Keys.PK_TEST_BAZ;
    }

    private transient TestBarLinkPath _testBarLink;

    /**
     * Get the implicit to-many join path to the
     * <code>public.test_bar_link</code> table
     */
    public TestBarLinkPath testBarLink() {
        if (_testBarLink == null)
            _testBarLink = new TestBarLinkPath(this, null, Keys.TEST_BAR_LINK__FK_TEST_BAR_LINK_TO_BAZ.getInverseKey());

        return _testBarLink;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.test_bar</code> table
     */
    public TestBarPath testBar() {
        return testBarLink().testBar();
    }

    @Override
    public TestBaz as(String alias) {
        return new TestBaz(DSL.name(alias), this);
    }

    @Override
    public TestBaz as(Name alias) {
        return new TestBaz(alias, this);
    }

    @Override
    public TestBaz as(Table<?> alias) {
        return new TestBaz(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TestBaz rename(String name) {
        return new TestBaz(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TestBaz rename(Name name) {
        return new TestBaz(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TestBaz rename(Table<?> name) {
        return new TestBaz(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestBaz where(Condition condition) {
        return new TestBaz(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestBaz where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestBaz where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestBaz where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestBaz where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestBaz where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestBaz where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestBaz where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestBaz whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestBaz whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
