/*
 * This file is generated by jOOQ.
 */
package com.dataciders.qlivetest.domain;


import com.dataciders.qlivetest.domain.tables.AppLogin;
import com.dataciders.qlivetest.domain.tables.AppUser;
import com.dataciders.qlivetest.domain.tables.Bar;
import com.dataciders.qlivetest.domain.tables.BarLink;
import com.dataciders.qlivetest.domain.tables.Baz;
import com.dataciders.qlivetest.domain.tables.Foo;
import com.dataciders.qlivetest.domain.tables.FooType;
import com.dataciders.qlivetest.domain.tables.Qux;
import com.dataciders.qlivetest.domain.tables.records.AppLoginRecord;
import com.dataciders.qlivetest.domain.tables.records.AppUserRecord;
import com.dataciders.qlivetest.domain.tables.records.BarLinkRecord;
import com.dataciders.qlivetest.domain.tables.records.BarRecord;
import com.dataciders.qlivetest.domain.tables.records.BazRecord;
import com.dataciders.qlivetest.domain.tables.records.FooRecord;
import com.dataciders.qlivetest.domain.tables.records.FooTypeRecord;
import com.dataciders.qlivetest.domain.tables.records.QuxRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AppLoginRecord> PK_APP_LOGIN = Internal.createUniqueKey(AppLogin.APP_LOGIN, DSL.name("pk_app_login"), new TableField[] { AppLogin.APP_LOGIN.SERIES }, true);
    public static final UniqueKey<AppUserRecord> PK_APP_USER = Internal.createUniqueKey(AppUser.APP_USER, DSL.name("pk_app_user"), new TableField[] { AppUser.APP_USER.ID }, true);
    public static final UniqueKey<AppUserRecord> UC_APP_USER_LOGIN = Internal.createUniqueKey(AppUser.APP_USER, DSL.name("uc_app_user_login"), new TableField[] { AppUser.APP_USER.LOGIN }, true);
    public static final UniqueKey<BarRecord> PK_BAR = Internal.createUniqueKey(Bar.BAR, DSL.name("pk_bar"), new TableField[] { Bar.BAR.ID }, true);
    public static final UniqueKey<BarLinkRecord> PK_BAR_LINK = Internal.createUniqueKey(BarLink.BAR_LINK, DSL.name("pk_bar_link"), new TableField[] { BarLink.BAR_LINK.ID }, true);
    public static final UniqueKey<BazRecord> PK_BAZ = Internal.createUniqueKey(Baz.BAZ, DSL.name("pk_baz"), new TableField[] { Baz.BAZ.ID }, true);
    public static final UniqueKey<FooRecord> PK_FOO = Internal.createUniqueKey(Foo.FOO, DSL.name("pk_foo"), new TableField[] { Foo.FOO.ID }, true);
    public static final UniqueKey<FooTypeRecord> FOO_TYPE_NAME_KEY = Internal.createUniqueKey(FooType.FOO_TYPE, DSL.name("foo_type_name_key"), new TableField[] { FooType.FOO_TYPE.NAME }, true);
    public static final UniqueKey<FooTypeRecord> PK_FOO_TYPE = Internal.createUniqueKey(FooType.FOO_TYPE, DSL.name("pk_foo_type"), new TableField[] { FooType.FOO_TYPE.ORDINAL }, true);
    public static final UniqueKey<QuxRecord> PK_QUX = Internal.createUniqueKey(Qux.QUX, DSL.name("pk_qux"), new TableField[] { Qux.QUX.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BarLinkRecord, BarRecord> BAR_LINK__FK_BAR_LINK_TO_BAR = Internal.createForeignKey(BarLink.BAR_LINK, DSL.name("fk_bar_link_to_bar"), new TableField[] { BarLink.BAR_LINK.BAR_ID }, Keys.PK_BAR, new TableField[] { Bar.BAR.ID }, true);
    public static final ForeignKey<BarLinkRecord, BazRecord> BAR_LINK__FK_BAR_LINK_TO_BAZ = Internal.createForeignKey(BarLink.BAR_LINK, DSL.name("fk_bar_link_to_baz"), new TableField[] { BarLink.BAR_LINK.BAZ_ID }, Keys.PK_BAZ, new TableField[] { Baz.BAZ.ID }, true);
    public static final ForeignKey<FooRecord, AppUserRecord> FOO__FK_FOO_OWNER_ID = Internal.createForeignKey(Foo.FOO, DSL.name("fk_foo_owner_id"), new TableField[] { Foo.FOO.OWNER_ID }, Keys.PK_APP_USER, new TableField[] { AppUser.APP_USER.ID }, true);
    public static final ForeignKey<FooRecord, FooTypeRecord> FOO__FK_FOO_TYPE_ID = Internal.createForeignKey(Foo.FOO, DSL.name("fk_foo_type_id"), new TableField[] { Foo.FOO.TYPE }, Keys.FOO_TYPE_NAME_KEY, new TableField[] { FooType.FOO_TYPE.NAME }, true);
}
