/*
 * This file is generated by jOOQ.
 */
package com.dataciders.qlivetest.domain;


import com.dataciders.qlivetest.domain.tables.AppLogin;
import com.dataciders.qlivetest.domain.tables.AppUser;
import com.dataciders.qlivetest.domain.tables.Bar;
import com.dataciders.qlivetest.domain.tables.BarLink;
import com.dataciders.qlivetest.domain.tables.Baz;
import com.dataciders.qlivetest.domain.tables.Foo;
import com.dataciders.qlivetest.domain.tables.FooType;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.app_login</code>.
     */
    public final AppLogin APP_LOGIN = AppLogin.APP_LOGIN;

    /**
     * The table <code>public.app_user</code>.
     */
    public final AppUser APP_USER = AppUser.APP_USER;

    /**
     * The table <code>public.bar</code>.
     */
    public final Bar BAR = Bar.BAR;

    /**
     * The table <code>public.bar_link</code>.
     */
    public final BarLink BAR_LINK = BarLink.BAR_LINK;

    /**
     * The table <code>public.baz</code>.
     */
    public final Baz BAZ = Baz.BAZ;

    /**
     * The table <code>public.foo</code>.
     */
    public final Foo FOO = Foo.FOO;

    /**
     * The table <code>public.foo_type</code>.
     */
    public final FooType FOO_TYPE = FooType.FOO_TYPE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AppLogin.APP_LOGIN,
            AppUser.APP_USER,
            Bar.BAR,
            BarLink.BAR_LINK,
            Baz.BAZ,
            Foo.FOO,
            FooType.FOO_TYPE
        );
    }
}
