/*
 * This file is generated by jOOQ.
 */
package com.dataciders.qlivetest.domain;


import com.dataciders.qlivetest.domain.tables.AppFieldLayout;
import com.dataciders.qlivetest.domain.tables.AppLogin;
import com.dataciders.qlivetest.domain.tables.AppUser;
import com.dataciders.qlivetest.domain.tables.AppVersion;
import com.dataciders.qlivetest.domain.tables.Bar;
import com.dataciders.qlivetest.domain.tables.BarLink;
import com.dataciders.qlivetest.domain.tables.Baz;
import com.dataciders.qlivetest.domain.tables.Foo;
import com.dataciders.qlivetest.domain.tables.FooType;
import com.dataciders.qlivetest.domain.tables.Qux;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.app_field_layout</code>.
     */
    public static final AppFieldLayout APP_FIELD_LAYOUT = AppFieldLayout.APP_FIELD_LAYOUT;

    /**
     * The table <code>public.app_login</code>.
     */
    public static final AppLogin APP_LOGIN = AppLogin.APP_LOGIN;

    /**
     * The table <code>public.app_user</code>.
     */
    public static final AppUser APP_USER = AppUser.APP_USER;

    /**
     * The table <code>public.app_version</code>.
     */
    public static final AppVersion APP_VERSION = AppVersion.APP_VERSION;

    /**
     * The table <code>public.bar</code>.
     */
    public static final Bar BAR = Bar.BAR;

    /**
     * The table <code>public.bar_link</code>.
     */
    public static final BarLink BAR_LINK = BarLink.BAR_LINK;

    /**
     * The table <code>public.baz</code>.
     */
    public static final Baz BAZ = Baz.BAZ;

    /**
     * The table <code>public.foo</code>.
     */
    public static final Foo FOO = Foo.FOO;

    /**
     * The table <code>public.foo_type</code>.
     */
    public static final FooType FOO_TYPE = FooType.FOO_TYPE;

    /**
     * Every scalar type a column can hold, for exercising the scalar handling
     * end to end
     */
    public static final Qux QUX = Qux.QUX;
}
