/*
 * This file is generated by jOOQ.
 */
package com.dataciders.qlivetest.domain.tables;


import com.dataciders.qlivetest.domain.Keys;
import com.dataciders.qlivetest.domain.Public;
import com.dataciders.qlivetest.domain.tables.records.AppFieldLayoutRecord;

import java.sql.Timestamp;
import java.util.Collection;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AppFieldLayout extends TableImpl<AppFieldLayoutRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.app_field_layout</code>
     */
    public static final AppFieldLayout APP_FIELD_LAYOUT = new AppFieldLayout();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppFieldLayoutRecord> getRecordType() {
        return AppFieldLayoutRecord.class;
    }

    /**
     * The column <code>public.app_field_layout.id</code>.
     */
    public final TableField<AppFieldLayoutRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.app_field_layout.entity_type</code>.
     */
    public final TableField<AppFieldLayoutRecord, String> ENTITY_TYPE = createField(DSL.name("entity_type"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.app_field_layout.fields</code>.
     */
    public final TableField<AppFieldLayoutRecord, String> FIELDS = createField(DSL.name("fields"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.app_field_layout.created</code>.
     */
    public final TableField<AppFieldLayoutRecord, Timestamp> CREATED = createField(DSL.name("created"), SQLDataType.TIMESTAMP(6).nullable(false), this, "");

    private AppFieldLayout(Name alias, Table<AppFieldLayoutRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AppFieldLayout(Name alias, Table<AppFieldLayoutRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.app_field_layout</code> table reference
     */
    public AppFieldLayout(String alias) {
        this(DSL.name(alias), APP_FIELD_LAYOUT);
    }

    /**
     * Create an aliased <code>public.app_field_layout</code> table reference
     */
    public AppFieldLayout(Name alias) {
        this(alias, APP_FIELD_LAYOUT);
    }

    /**
     * Create a <code>public.app_field_layout</code> table reference
     */
    public AppFieldLayout() {
        this(DSL.name("app_field_layout"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AppFieldLayoutRecord> getPrimaryKey() {
        return Keys.PK_APP_FIELD_LAYOUT;
    }

    @Override
    public AppFieldLayout as(String alias) {
        return new AppFieldLayout(DSL.name(alias), this);
    }

    @Override
    public AppFieldLayout as(Name alias) {
        return new AppFieldLayout(alias, this);
    }

    @Override
    public AppFieldLayout as(Table<?> alias) {
        return new AppFieldLayout(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AppFieldLayout rename(String name) {
        return new AppFieldLayout(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppFieldLayout rename(Name name) {
        return new AppFieldLayout(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppFieldLayout rename(Table<?> name) {
        return new AppFieldLayout(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppFieldLayout where(Condition condition) {
        return new AppFieldLayout(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppFieldLayout where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppFieldLayout where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppFieldLayout where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppFieldLayout where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppFieldLayout where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppFieldLayout where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppFieldLayout where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppFieldLayout whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppFieldLayout whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
