/*
 * This file is generated by jOOQ.
 */
package com.dataciders.qlivetest.domain.tables;


import com.dataciders.qlivetest.domain.Keys;
import com.dataciders.qlivetest.domain.Public;
import com.dataciders.qlivetest.domain.tables.AppUser.AppUserPath;
import com.dataciders.qlivetest.domain.tables.records.AppVersionRecord;

import java.math.BigInteger;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AppVersion extends TableImpl<AppVersionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.app_version</code>
     */
    public static final AppVersion APP_VERSION = new AppVersion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppVersionRecord> getRecordType() {
        return AppVersionRecord.class;
    }

    /**
     * The column <code>public.app_version.id</code>.
     */
    public final TableField<AppVersionRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.app_version.field_mask</code>.
     */
    public final TableField<AppVersionRecord, BigInteger> FIELD_MASK = createField(DSL.name("field_mask"), SQLDataType.DECIMAL_INTEGER(39).nullable(false), this, "");

    /**
     * The column <code>public.app_version.owner_id</code>.
     */
    public final TableField<AppVersionRecord, String> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.app_version.created</code>.
     */
    public final TableField<AppVersionRecord, Timestamp> CREATED = createField(DSL.name("created"), SQLDataType.TIMESTAMP(6).nullable(false), this, "");

    /**
     * The column <code>public.app_version.entity_type</code>.
     */
    public final TableField<AppVersionRecord, String> ENTITY_TYPE = createField(DSL.name("entity_type"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.app_version.entity_id</code>.
     */
    public final TableField<AppVersionRecord, String> ENTITY_ID = createField(DSL.name("entity_id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.app_version.prev</code>.
     */
    public final TableField<AppVersionRecord, String> PREV = createField(DSL.name("prev"), SQLDataType.VARCHAR(36), this, "");

    /**
     * The column <code>public.app_version.field_layout</code>.
     */
    public final TableField<AppVersionRecord, String> FIELD_LAYOUT = createField(DSL.name("field_layout"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    private AppVersion(Name alias, Table<AppVersionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AppVersion(Name alias, Table<AppVersionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.app_version</code> table reference
     */
    public AppVersion(String alias) {
        this(DSL.name(alias), APP_VERSION);
    }

    /**
     * Create an aliased <code>public.app_version</code> table reference
     */
    public AppVersion(Name alias) {
        this(alias, APP_VERSION);
    }

    /**
     * Create a <code>public.app_version</code> table reference
     */
    public AppVersion() {
        this(DSL.name("app_version"), null);
    }

    public <O extends Record> AppVersion(Table<O> path, ForeignKey<O, AppVersionRecord> childPath, InverseForeignKey<O, AppVersionRecord> parentPath) {
        super(path, childPath, parentPath, APP_VERSION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.30"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class AppVersionPath extends AppVersion implements Path<AppVersionRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AppVersionPath(Table<O> path, ForeignKey<O, AppVersionRecord> childPath, InverseForeignKey<O, AppVersionRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AppVersionPath(Name alias, Table<AppVersionRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AppVersionPath as(String alias) {
            return new AppVersionPath(DSL.name(alias), this);
        }

        @Override
        public AppVersionPath as(Name alias) {
            return new AppVersionPath(alias, this);
        }

        @Override
        public AppVersionPath as(Table<?> alias) {
            return new AppVersionPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AppVersionRecord> getPrimaryKey() {
        return Keys.PK_APP_VERSION;
    }

    @Override
    public List<ForeignKey<AppVersionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.APP_VERSION__FK_APP_VERSION_OWNER_ID);
    }

    private transient AppUserPath _appUser;

    /**
     * Get the implicit join path to the <code>public.app_user</code> table.
     */
    public AppUserPath appUser() {
        if (_appUser == null)
            _appUser = new AppUserPath(this, Keys.APP_VERSION__FK_APP_VERSION_OWNER_ID, null);

        return _appUser;
    }

    @Override
    public AppVersion as(String alias) {
        return new AppVersion(DSL.name(alias), this);
    }

    @Override
    public AppVersion as(Name alias) {
        return new AppVersion(alias, this);
    }

    @Override
    public AppVersion as(Table<?> alias) {
        return new AppVersion(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AppVersion rename(String name) {
        return new AppVersion(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppVersion rename(Name name) {
        return new AppVersion(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppVersion rename(Table<?> name) {
        return new AppVersion(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppVersion where(Condition condition) {
        return new AppVersion(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppVersion where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppVersion where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppVersion where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppVersion where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppVersion where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppVersion where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AppVersion where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppVersion whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AppVersion whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
