/*
 * This file is generated by jOOQ.
 */
package com.dataciders.qlivetest.domain.tables;


import com.dataciders.qlivetest.domain.Keys;
import com.dataciders.qlivetest.domain.Public;
import com.dataciders.qlivetest.domain.tables.Bar.BarPath;
import com.dataciders.qlivetest.domain.tables.Baz.BazPath;
import com.dataciders.qlivetest.domain.tables.records.BarLinkRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BarLink extends TableImpl<BarLinkRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.bar_link</code>
     */
    public static final BarLink BAR_LINK = new BarLink();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BarLinkRecord> getRecordType() {
        return BarLinkRecord.class;
    }

    /**
     * The column <code>public.bar_link.id</code>.
     */
    public final TableField<BarLinkRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.bar_link.bar_id</code>.
     */
    public final TableField<BarLinkRecord, String> BAR_ID = createField(DSL.name("bar_id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.bar_link.baz_id</code>.
     */
    public final TableField<BarLinkRecord, String> BAZ_ID = createField(DSL.name("baz_id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.bar_link.version</code>.
     */
    public final TableField<BarLinkRecord, String> VERSION = createField(DSL.name("version"), SQLDataType.VARCHAR(36), this, "");

    private BarLink(Name alias, Table<BarLinkRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BarLink(Name alias, Table<BarLinkRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.bar_link</code> table reference
     */
    public BarLink(String alias) {
        this(DSL.name(alias), BAR_LINK);
    }

    /**
     * Create an aliased <code>public.bar_link</code> table reference
     */
    public BarLink(Name alias) {
        this(alias, BAR_LINK);
    }

    /**
     * Create a <code>public.bar_link</code> table reference
     */
    public BarLink() {
        this(DSL.name("bar_link"), null);
    }

    public <O extends Record> BarLink(Table<O> path, ForeignKey<O, BarLinkRecord> childPath, InverseForeignKey<O, BarLinkRecord> parentPath) {
        super(path, childPath, parentPath, BAR_LINK);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.30"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class BarLinkPath extends BarLink implements Path<BarLinkRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> BarLinkPath(Table<O> path, ForeignKey<O, BarLinkRecord> childPath, InverseForeignKey<O, BarLinkRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private BarLinkPath(Name alias, Table<BarLinkRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BarLinkPath as(String alias) {
            return new BarLinkPath(DSL.name(alias), this);
        }

        @Override
        public BarLinkPath as(Name alias) {
            return new BarLinkPath(alias, this);
        }

        @Override
        public BarLinkPath as(Table<?> alias) {
            return new BarLinkPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<BarLinkRecord> getPrimaryKey() {
        return Keys.PK_BAR_LINK;
    }

    @Override
    public List<ForeignKey<BarLinkRecord, ?>> getReferences() {
        return Arrays.asList(Keys.BAR_LINK__FK_BAR_LINK_TO_BAR, Keys.BAR_LINK__FK_BAR_LINK_TO_BAZ);
    }

    private transient BarPath _bar;

    /**
     * Get the implicit join path to the <code>public.bar</code> table.
     */
    public BarPath bar() {
        if (_bar == null)
            _bar = new BarPath(this, Keys.BAR_LINK__FK_BAR_LINK_TO_BAR, null);

        return _bar;
    }

    private transient BazPath _baz;

    /**
     * Get the implicit join path to the <code>public.baz</code> table.
     */
    public BazPath baz() {
        if (_baz == null)
            _baz = new BazPath(this, Keys.BAR_LINK__FK_BAR_LINK_TO_BAZ, null);

        return _baz;
    }

    @Override
    public BarLink as(String alias) {
        return new BarLink(DSL.name(alias), this);
    }

    @Override
    public BarLink as(Name alias) {
        return new BarLink(alias, this);
    }

    @Override
    public BarLink as(Table<?> alias) {
        return new BarLink(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BarLink rename(String name) {
        return new BarLink(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BarLink rename(Name name) {
        return new BarLink(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BarLink rename(Table<?> name) {
        return new BarLink(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BarLink where(Condition condition) {
        return new BarLink(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BarLink where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BarLink where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BarLink where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BarLink where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BarLink where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BarLink where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BarLink where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BarLink whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BarLink whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
