/*
 * This file is generated by jOOQ.
 */
package com.dataciders.qlivetest.domain.tables;


import com.dataciders.qlivetest.domain.Keys;
import com.dataciders.qlivetest.domain.Public;
import com.dataciders.qlivetest.domain.tables.BarLink.BarLinkPath;
import com.dataciders.qlivetest.domain.tables.records.BazRecord;

import java.sql.Timestamp;
import java.util.Collection;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Baz extends TableImpl<BazRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.baz</code>
     */
    public static final Baz BAZ = new Baz();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BazRecord> getRecordType() {
        return BazRecord.class;
    }

    /**
     * The column <code>public.baz.id</code>.
     */
    public final TableField<BazRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.baz.name</code>.
     */
    public final TableField<BazRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.baz.num</code>.
     */
    public final TableField<BazRecord, Integer> NUM = createField(DSL.name("num"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.baz.created</code>.
     */
    public final TableField<BazRecord, Timestamp> CREATED = createField(DSL.name("created"), SQLDataType.TIMESTAMP(6).nullable(false), this, "");

    /**
     * The column <code>public.baz.description</code>.
     */
    public final TableField<BazRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.baz.version</code>.
     */
    public final TableField<BazRecord, String> VERSION = createField(DSL.name("version"), SQLDataType.VARCHAR(36), this, "");

    private Baz(Name alias, Table<BazRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Baz(Name alias, Table<BazRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.baz</code> table reference
     */
    public Baz(String alias) {
        this(DSL.name(alias), BAZ);
    }

    /**
     * Create an aliased <code>public.baz</code> table reference
     */
    public Baz(Name alias) {
        this(alias, BAZ);
    }

    /**
     * Create a <code>public.baz</code> table reference
     */
    public Baz() {
        this(DSL.name("baz"), null);
    }

    public <O extends Record> Baz(Table<O> path, ForeignKey<O, BazRecord> childPath, InverseForeignKey<O, BazRecord> parentPath) {
        super(path, childPath, parentPath, BAZ);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.30"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class BazPath extends Baz implements Path<BazRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> BazPath(Table<O> path, ForeignKey<O, BazRecord> childPath, InverseForeignKey<O, BazRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private BazPath(Name alias, Table<BazRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BazPath as(String alias) {
            return new BazPath(DSL.name(alias), this);
        }

        @Override
        public BazPath as(Name alias) {
            return new BazPath(alias, this);
        }

        @Override
        public BazPath as(Table<?> alias) {
            return new BazPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<BazRecord> getPrimaryKey() {
        return Keys.PK_BAZ;
    }

    private transient BarLinkPath _barLink;

    /**
     * Get the implicit to-many join path to the <code>public.bar_link</code>
     * table
     */
    public BarLinkPath barLink() {
        if (_barLink == null)
            _barLink = new BarLinkPath(this, null, Keys.BAR_LINK__FK_BAR_LINK_TO_BAZ.getInverseKey());

        return _barLink;
    }

    @Override
    public Baz as(String alias) {
        return new Baz(DSL.name(alias), this);
    }

    @Override
    public Baz as(Name alias) {
        return new Baz(alias, this);
    }

    @Override
    public Baz as(Table<?> alias) {
        return new Baz(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Baz rename(String name) {
        return new Baz(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Baz rename(Name name) {
        return new Baz(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Baz rename(Table<?> name) {
        return new Baz(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Baz where(Condition condition) {
        return new Baz(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Baz where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Baz where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Baz where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Baz where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Baz where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Baz where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Baz where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Baz whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Baz whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
