/*
 * This file is generated by jOOQ.
 */
package com.dataciders.qlive.testdomain.tables;


import com.dataciders.qlive.testdomain.Keys;
import com.dataciders.qlive.testdomain.Public;
import com.dataciders.qlive.testdomain.tables.TestFooType.TestFooTypePath;
import com.dataciders.qlive.testdomain.tables.TestUser.TestUserPath;
import com.dataciders.qlive.testdomain.tables.records.TestFooRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TestFoo extends TableImpl<TestFooRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.test_foo</code>
     */
    public static final TestFoo TEST_FOO = new TestFoo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TestFooRecord> getRecordType() {
        return TestFooRecord.class;
    }

    /**
     * The column <code>public.test_foo.id</code>.
     */
    public final TableField<TestFooRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.test_foo.name</code>.
     */
    public final TableField<TestFooRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.test_foo.num</code>.
     */
    public final TableField<TestFooRecord, Integer> NUM = createField(DSL.name("num"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.test_foo.type</code>.
     */
    public final TableField<TestFooRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.test_foo.created</code>.
     */
    public final TableField<TestFooRecord, Timestamp> CREATED = createField(DSL.name("created"), SQLDataType.TIMESTAMP(6).nullable(false), this, "");

    /**
     * The column <code>public.test_foo.description</code>.
     */
    public final TableField<TestFooRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.test_foo.owner_id</code>.
     */
    public final TableField<TestFooRecord, String> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.test_foo.flag</code>.
     */
    public final TableField<TestFooRecord, Boolean> FLAG = createField(DSL.name("flag"), SQLDataType.BOOLEAN.nullable(false), this, "");

    private TestFoo(Name alias, Table<TestFooRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TestFoo(Name alias, Table<TestFooRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.test_foo</code> table reference
     */
    public TestFoo(String alias) {
        this(DSL.name(alias), TEST_FOO);
    }

    /**
     * Create an aliased <code>public.test_foo</code> table reference
     */
    public TestFoo(Name alias) {
        this(alias, TEST_FOO);
    }

    /**
     * Create a <code>public.test_foo</code> table reference
     */
    public TestFoo() {
        this(DSL.name("test_foo"), null);
    }

    public <O extends Record> TestFoo(Table<O> path, ForeignKey<O, TestFooRecord> childPath, InverseForeignKey<O, TestFooRecord> parentPath) {
        super(path, childPath, parentPath, TEST_FOO);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.30"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class TestFooPath extends TestFoo implements Path<TestFooRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TestFooPath(Table<O> path, ForeignKey<O, TestFooRecord> childPath, InverseForeignKey<O, TestFooRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TestFooPath(Name alias, Table<TestFooRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TestFooPath as(String alias) {
            return new TestFooPath(DSL.name(alias), this);
        }

        @Override
        public TestFooPath as(Name alias) {
            return new TestFooPath(alias, this);
        }

        @Override
        public TestFooPath as(Table<?> alias) {
            return new TestFooPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TestFooRecord> getPrimaryKey() {
        return Keys.PK_TEST_FOO;
    }

    @Override
    public List<ForeignKey<TestFooRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TEST_FOO__FK_TEST_FOO_OWNER_ID, Keys.TEST_FOO__FK_TEST_FOO_TYPE_ID);
    }

    private transient TestUserPath _testUser;

    /**
     * Get the implicit join path to the <code>public.test_user</code> table.
     */
    public TestUserPath testUser() {
        if (_testUser == null)
            _testUser = new TestUserPath(this, Keys.TEST_FOO__FK_TEST_FOO_OWNER_ID, null);

        return _testUser;
    }

    private transient TestFooTypePath _testFooType;

    /**
     * Get the implicit join path to the <code>public.test_foo_type</code>
     * table.
     */
    public TestFooTypePath testFooType() {
        if (_testFooType == null)
            _testFooType = new TestFooTypePath(this, Keys.TEST_FOO__FK_TEST_FOO_TYPE_ID, null);

        return _testFooType;
    }

    @Override
    public TestFoo as(String alias) {
        return new TestFoo(DSL.name(alias), this);
    }

    @Override
    public TestFoo as(Name alias) {
        return new TestFoo(alias, this);
    }

    @Override
    public TestFoo as(Table<?> alias) {
        return new TestFoo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TestFoo rename(String name) {
        return new TestFoo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TestFoo rename(Name name) {
        return new TestFoo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TestFoo rename(Table<?> name) {
        return new TestFoo(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestFoo where(Condition condition) {
        return new TestFoo(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestFoo where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestFoo where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestFoo where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestFoo where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestFoo where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestFoo where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestFoo where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestFoo whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestFoo whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
