/*
 * This file is generated by jOOQ.
 */
package com.dataciders.qlive.testdomain.tables;


import com.dataciders.qlive.testdomain.Keys;
import com.dataciders.qlive.testdomain.Public;
import com.dataciders.qlive.testdomain.tables.TestFoo.TestFooPath;
import com.dataciders.qlive.testdomain.tables.records.TestUserRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TestUser extends TableImpl<TestUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.test_user</code>
     */
    public static final TestUser TEST_USER = new TestUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TestUserRecord> getRecordType() {
        return TestUserRecord.class;
    }

    /**
     * The column <code>public.test_user.id</code>.
     */
    public final TableField<TestUserRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.test_user.login</code>.
     */
    public final TableField<TestUserRecord, String> LOGIN = createField(DSL.name("login"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.test_user.password</code>.
     */
    public final TableField<TestUserRecord, String> PASSWORD = createField(DSL.name("password"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.test_user.disabled</code>.
     */
    public final TableField<TestUserRecord, Boolean> DISABLED = createField(DSL.name("disabled"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.test_user.created</code>.
     */
    public final TableField<TestUserRecord, Timestamp> CREATED = createField(DSL.name("created"), SQLDataType.TIMESTAMP(6).nullable(false), this, "");

    /**
     * The column <code>public.test_user.last_login</code>.
     */
    public final TableField<TestUserRecord, Timestamp> LAST_LOGIN = createField(DSL.name("last_login"), SQLDataType.TIMESTAMP(6), this, "");

    /**
     * The column <code>public.test_user.roles</code>.
     */
    public final TableField<TestUserRecord, String> ROLES = createField(DSL.name("roles"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private TestUser(Name alias, Table<TestUserRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TestUser(Name alias, Table<TestUserRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.test_user</code> table reference
     */
    public TestUser(String alias) {
        this(DSL.name(alias), TEST_USER);
    }

    /**
     * Create an aliased <code>public.test_user</code> table reference
     */
    public TestUser(Name alias) {
        this(alias, TEST_USER);
    }

    /**
     * Create a <code>public.test_user</code> table reference
     */
    public TestUser() {
        this(DSL.name("test_user"), null);
    }

    public <O extends Record> TestUser(Table<O> path, ForeignKey<O, TestUserRecord> childPath, InverseForeignKey<O, TestUserRecord> parentPath) {
        super(path, childPath, parentPath, TEST_USER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.30"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class TestUserPath extends TestUser implements Path<TestUserRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TestUserPath(Table<O> path, ForeignKey<O, TestUserRecord> childPath, InverseForeignKey<O, TestUserRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TestUserPath(Name alias, Table<TestUserRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TestUserPath as(String alias) {
            return new TestUserPath(DSL.name(alias), this);
        }

        @Override
        public TestUserPath as(Name alias) {
            return new TestUserPath(alias, this);
        }

        @Override
        public TestUserPath as(Table<?> alias) {
            return new TestUserPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TestUserRecord> getPrimaryKey() {
        return Keys.PK_TEST_USER;
    }

    @Override
    public List<UniqueKey<TestUserRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UC_TEST_USER_LOGIN);
    }

    private transient TestFooPath _testFoo;

    /**
     * Get the implicit to-many join path to the <code>public.test_foo</code>
     * table
     */
    public TestFooPath testFoo() {
        if (_testFoo == null)
            _testFoo = new TestFooPath(this, null, Keys.TEST_FOO__FK_TEST_FOO_OWNER_ID.getInverseKey());

        return _testFoo;
    }

    @Override
    public TestUser as(String alias) {
        return new TestUser(DSL.name(alias), this);
    }

    @Override
    public TestUser as(Name alias) {
        return new TestUser(alias, this);
    }

    @Override
    public TestUser as(Table<?> alias) {
        return new TestUser(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TestUser rename(String name) {
        return new TestUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TestUser rename(Name name) {
        return new TestUser(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TestUser rename(Table<?> name) {
        return new TestUser(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestUser where(Condition condition) {
        return new TestUser(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestUser where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestUser where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestUser where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestUser where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestUser where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestUser where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestUser where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestUser whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestUser whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
