/*
 * This file is generated by jOOQ.
 */
package com.dataciders.qlive.testdomain.tables;


import com.dataciders.qlive.testdomain.Keys;
import com.dataciders.qlive.testdomain.Public;
import com.dataciders.qlive.testdomain.tables.TestFoo.TestFooPath;
import com.dataciders.qlive.testdomain.tables.records.TestFooTypeRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TestFooType extends TableImpl<TestFooTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.test_foo_type</code>
     */
    public static final TestFooType TEST_FOO_TYPE = new TestFooType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TestFooTypeRecord> getRecordType() {
        return TestFooTypeRecord.class;
    }

    /**
     * The column <code>public.test_foo_type.ordinal</code>.
     */
    public final TableField<TestFooTypeRecord, Integer> ORDINAL = createField(DSL.name("ordinal"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.test_foo_type.name</code>.
     */
    public final TableField<TestFooTypeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private TestFooType(Name alias, Table<TestFooTypeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TestFooType(Name alias, Table<TestFooTypeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.test_foo_type</code> table reference
     */
    public TestFooType(String alias) {
        this(DSL.name(alias), TEST_FOO_TYPE);
    }

    /**
     * Create an aliased <code>public.test_foo_type</code> table reference
     */
    public TestFooType(Name alias) {
        this(alias, TEST_FOO_TYPE);
    }

    /**
     * Create a <code>public.test_foo_type</code> table reference
     */
    public TestFooType() {
        this(DSL.name("test_foo_type"), null);
    }

    public <O extends Record> TestFooType(Table<O> path, ForeignKey<O, TestFooTypeRecord> childPath, InverseForeignKey<O, TestFooTypeRecord> parentPath) {
        super(path, childPath, parentPath, TEST_FOO_TYPE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.30"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class TestFooTypePath extends TestFooType implements Path<TestFooTypeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TestFooTypePath(Table<O> path, ForeignKey<O, TestFooTypeRecord> childPath, InverseForeignKey<O, TestFooTypeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TestFooTypePath(Name alias, Table<TestFooTypeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TestFooTypePath as(String alias) {
            return new TestFooTypePath(DSL.name(alias), this);
        }

        @Override
        public TestFooTypePath as(Name alias) {
            return new TestFooTypePath(alias, this);
        }

        @Override
        public TestFooTypePath as(Table<?> alias) {
            return new TestFooTypePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TestFooTypeRecord> getPrimaryKey() {
        return Keys.PK_TEST_FOO_TYPE;
    }

    @Override
    public List<UniqueKey<TestFooTypeRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.TEST_FOO_TYPE_NAME_KEY);
    }

    private transient TestFooPath _testFoo;

    /**
     * Get the implicit to-many join path to the <code>public.test_foo</code>
     * table
     */
    public TestFooPath testFoo() {
        if (_testFoo == null)
            _testFoo = new TestFooPath(this, null, Keys.TEST_FOO__FK_TEST_FOO_TYPE_ID.getInverseKey());

        return _testFoo;
    }

    @Override
    public TestFooType as(String alias) {
        return new TestFooType(DSL.name(alias), this);
    }

    @Override
    public TestFooType as(Name alias) {
        return new TestFooType(alias, this);
    }

    @Override
    public TestFooType as(Table<?> alias) {
        return new TestFooType(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TestFooType rename(String name) {
        return new TestFooType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TestFooType rename(Name name) {
        return new TestFooType(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TestFooType rename(Table<?> name) {
        return new TestFooType(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestFooType where(Condition condition) {
        return new TestFooType(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestFooType where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestFooType where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestFooType where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestFooType where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestFooType where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestFooType where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestFooType where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestFooType whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestFooType whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
