/*
 * This file is generated by jOOQ.
 */
package io.github.qlivedev.qlivetest.domain.tables.pojos;


import io.github.qlivedev.graphql.jooq.GeneratedDomainObject;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "app_field_layout",
    schema = "public"
)
public class AppFieldLayout extends GeneratedDomainObject implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String entityType;
    private String fields;
    private Timestamp created;

    public AppFieldLayout() {}

    public AppFieldLayout(AppFieldLayout value) {
        this.id = value.id;
        this.entityType = value.entityType;
        this.fields = value.fields;
        this.created = value.created;
    }

    public AppFieldLayout(
        String id,
        String entityType,
        String fields,
        Timestamp created
    ) {
        this.id = id;
        this.entityType = entityType;
        this.fields = fields;
        this.created = created;
    }

    /**
     * Getter for <code>public.app_field_layout.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.app_field_layout.id</code>.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.app_field_layout.entity_type</code>.
     */
    @Column(name = "entity_type", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getEntityType() {
        return this.entityType;
    }

    /**
     * Setter for <code>public.app_field_layout.entity_type</code>.
     */
    public void setEntityType(String entityType) {
        this.entityType = entityType;
    }

    /**
     * Getter for <code>public.app_field_layout.fields</code>.
     */
    @Column(name = "fields", nullable = false)
    @NotNull
    public String getFields() {
        return this.fields;
    }

    /**
     * Setter for <code>public.app_field_layout.fields</code>.
     */
    public void setFields(String fields) {
        this.fields = fields;
    }

    /**
     * Getter for <code>public.app_field_layout.created</code>.
     */
    @Column(name = "created", nullable = false, precision = 6)
    @NotNull
    public Timestamp getCreated() {
        return this.created;
    }

    /**
     * Setter for <code>public.app_field_layout.created</code>.
     */
    public void setCreated(Timestamp created) {
        this.created = created;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AppFieldLayout other = (AppFieldLayout) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.entityType == null) {
            if (other.entityType != null)
                return false;
        }
        else if (!this.entityType.equals(other.entityType))
            return false;
        if (this.fields == null) {
            if (other.fields != null)
                return false;
        }
        else if (!this.fields.equals(other.fields))
            return false;
        if (this.created == null) {
            if (other.created != null)
                return false;
        }
        else if (!this.created.equals(other.created))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.entityType == null) ? 0 : this.entityType.hashCode());
        result = prime * result + ((this.fields == null) ? 0 : this.fields.hashCode());
        result = prime * result + ((this.created == null) ? 0 : this.created.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AppFieldLayout (");

        sb.append(id);
        sb.append(", ").append(entityType);
        sb.append(", ").append(fields);
        sb.append(", ").append(created);

        sb.append(")");
        return sb.toString();
    }
}
