/*
 * This file is generated by jOOQ.
 */
package io.github.qlivedev.qlivetest.domain.tables.pojos;


import io.github.qlivedev.graphql.jooq.GeneratedDomainObject;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "bar_link",
    schema = "public",
    uniqueConstraints = {
        @UniqueConstraint(name = "uc_bar_link_bar_baz", columnNames = { "bar_id", "baz_id" })
    }
)
public class BarLink extends GeneratedDomainObject implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String barId;
    private String bazId;
    private String version;

    public BarLink() {}

    public BarLink(BarLink value) {
        this.id = value.id;
        this.barId = value.barId;
        this.bazId = value.bazId;
        this.version = value.version;
    }

    public BarLink(
        String id,
        String barId,
        String bazId,
        String version
    ) {
        this.id = id;
        this.barId = barId;
        this.bazId = bazId;
        this.version = version;
    }

    /**
     * Getter for <code>public.bar_link.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.bar_link.id</code>.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.bar_link.bar_id</code>.
     */
    @Column(name = "bar_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getBarId() {
        return this.barId;
    }

    /**
     * Setter for <code>public.bar_link.bar_id</code>.
     */
    public void setBarId(String barId) {
        this.barId = barId;
    }

    /**
     * Getter for <code>public.bar_link.baz_id</code>.
     */
    @Column(name = "baz_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getBazId() {
        return this.bazId;
    }

    /**
     * Setter for <code>public.bar_link.baz_id</code>.
     */
    public void setBazId(String bazId) {
        this.bazId = bazId;
    }

    /**
     * Getter for <code>public.bar_link.version</code>.
     */
    @Column(name = "version", length = 36)
    @Size(max = 36)
    public String getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>public.bar_link.version</code>.
     */
    public void setVersion(String version) {
        this.version = version;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final BarLink other = (BarLink) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.barId == null) {
            if (other.barId != null)
                return false;
        }
        else if (!this.barId.equals(other.barId))
            return false;
        if (this.bazId == null) {
            if (other.bazId != null)
                return false;
        }
        else if (!this.bazId.equals(other.bazId))
            return false;
        if (this.version == null) {
            if (other.version != null)
                return false;
        }
        else if (!this.version.equals(other.version))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.barId == null) ? 0 : this.barId.hashCode());
        result = prime * result + ((this.bazId == null) ? 0 : this.bazId.hashCode());
        result = prime * result + ((this.version == null) ? 0 : this.version.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BarLink (");

        sb.append(id);
        sb.append(", ").append(barId);
        sb.append(", ").append(bazId);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
