/*
 * This file is generated by jOOQ.
 */
package io.github.qlivedev.qlivetest.domain.tables.pojos;


import io.github.qlivedev.graphql.jooq.GeneratedDomainObject;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "quux",
    schema = "public"
)
public class Quux extends GeneratedDomainObject implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String name;
    private Integer numA;
    private Integer numB;
    private Timestamp created;

    public Quux() {}

    public Quux(Quux value) {
        this.id = value.id;
        this.name = value.name;
        this.numA = value.numA;
        this.numB = value.numB;
        this.created = value.created;
    }

    public Quux(
        String id,
        String name,
        Integer numA,
        Integer numB,
        Timestamp created
    ) {
        this.id = id;
        this.name = name;
        this.numA = numA;
        this.numB = numB;
        this.created = created;
    }

    /**
     * Getter for <code>public.quux.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.quux.id</code>.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.quux.name</code>.
     */
    @Column(name = "name", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.quux.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.quux.num_a</code>.
     */
    @Column(name = "num_a", nullable = false)
    @NotNull
    public Integer getNumA() {
        return this.numA;
    }

    /**
     * Setter for <code>public.quux.num_a</code>.
     */
    public void setNumA(Integer numA) {
        this.numA = numA;
    }

    /**
     * Getter for <code>public.quux.num_b</code>.
     */
    @Column(name = "num_b", nullable = false)
    @NotNull
    public Integer getNumB() {
        return this.numB;
    }

    /**
     * Setter for <code>public.quux.num_b</code>.
     */
    public void setNumB(Integer numB) {
        this.numB = numB;
    }

    /**
     * Getter for <code>public.quux.created</code>.
     */
    @Column(name = "created", nullable = false, precision = 6)
    @NotNull
    public Timestamp getCreated() {
        return this.created;
    }

    /**
     * Setter for <code>public.quux.created</code>.
     */
    public void setCreated(Timestamp created) {
        this.created = created;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Quux other = (Quux) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.numA == null) {
            if (other.numA != null)
                return false;
        }
        else if (!this.numA.equals(other.numA))
            return false;
        if (this.numB == null) {
            if (other.numB != null)
                return false;
        }
        else if (!this.numB.equals(other.numB))
            return false;
        if (this.created == null) {
            if (other.created != null)
                return false;
        }
        else if (!this.created.equals(other.created))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.numA == null) ? 0 : this.numA.hashCode());
        result = prime * result + ((this.numB == null) ? 0 : this.numB.hashCode());
        result = prime * result + ((this.created == null) ? 0 : this.created.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Quux (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(numA);
        sb.append(", ").append(numB);
        sb.append(", ").append(created);

        sb.append(")");
        return sb.toString();
    }
}
