/*
 * This file is generated by jOOQ.
 */
package io.github.qlivedev.qlivetest.domain.tables.pojos;


import io.github.qlivedev.graphql.jooq.GeneratedDomainObject;
import io.github.qlivedev.graphql.jsonb.JSONB;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;


/**
 * Every scalar type a column can hold, for exercising the scalar handling end
 * to end
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.30"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "qux",
    schema = "public"
)
public class Qux extends GeneratedDomainObject implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String name;
    private Boolean bool;
    private Integer intValue;
    private Double doubleValue;
    private String stringValue;
    private Timestamp timestampValue;
    private Date dateValue;
    private Long longValue;
    private Long currencyValue;
    private Byte byteValue;
    private BigDecimal bigDecimalValue;
    private JSONB jsonbValue;

    public Qux() {}

    public Qux(Qux value) {
        this.id = value.id;
        this.name = value.name;
        this.bool = value.bool;
        this.intValue = value.intValue;
        this.doubleValue = value.doubleValue;
        this.stringValue = value.stringValue;
        this.timestampValue = value.timestampValue;
        this.dateValue = value.dateValue;
        this.longValue = value.longValue;
        this.currencyValue = value.currencyValue;
        this.byteValue = value.byteValue;
        this.bigDecimalValue = value.bigDecimalValue;
        this.jsonbValue = value.jsonbValue;
    }

    public Qux(
        String id,
        String name,
        Boolean bool,
        Integer intValue,
        Double doubleValue,
        String stringValue,
        Timestamp timestampValue,
        Date dateValue,
        Long longValue,
        Long currencyValue,
        Byte byteValue,
        BigDecimal bigDecimalValue,
        JSONB jsonbValue
    ) {
        this.id = id;
        this.name = name;
        this.bool = bool;
        this.intValue = intValue;
        this.doubleValue = doubleValue;
        this.stringValue = stringValue;
        this.timestampValue = timestampValue;
        this.dateValue = dateValue;
        this.longValue = longValue;
        this.currencyValue = currencyValue;
        this.byteValue = byteValue;
        this.bigDecimalValue = bigDecimalValue;
        this.jsonbValue = jsonbValue;
    }

    /**
     * Getter for <code>public.qux.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.qux.id</code>.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.qux.name</code>.
     */
    @Column(name = "name", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.qux.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.qux.bool</code>.
     */
    @Column(name = "bool")
    public Boolean getBool() {
        return this.bool;
    }

    /**
     * Setter for <code>public.qux.bool</code>.
     */
    public void setBool(Boolean bool) {
        this.bool = bool;
    }

    /**
     * Getter for <code>public.qux.int_value</code>.
     */
    @Column(name = "int_value")
    public Integer getIntValue() {
        return this.intValue;
    }

    /**
     * Setter for <code>public.qux.int_value</code>.
     */
    public void setIntValue(Integer intValue) {
        this.intValue = intValue;
    }

    /**
     * Getter for <code>public.qux.double_value</code>.
     */
    @Column(name = "double_value")
    public Double getDoubleValue() {
        return this.doubleValue;
    }

    /**
     * Setter for <code>public.qux.double_value</code>.
     */
    public void setDoubleValue(Double doubleValue) {
        this.doubleValue = doubleValue;
    }

    /**
     * Getter for <code>public.qux.string_value</code>.
     */
    @Column(name = "string_value", length = 255)
    @Size(max = 255)
    public String getStringValue() {
        return this.stringValue;
    }

    /**
     * Setter for <code>public.qux.string_value</code>.
     */
    public void setStringValue(String stringValue) {
        this.stringValue = stringValue;
    }

    /**
     * Getter for <code>public.qux.timestamp_value</code>.
     */
    @Column(name = "timestamp_value", precision = 6)
    public Timestamp getTimestampValue() {
        return this.timestampValue;
    }

    /**
     * Setter for <code>public.qux.timestamp_value</code>.
     */
    public void setTimestampValue(Timestamp timestampValue) {
        this.timestampValue = timestampValue;
    }

    /**
     * Getter for <code>public.qux.date_value</code>.
     */
    @Column(name = "date_value")
    public Date getDateValue() {
        return this.dateValue;
    }

    /**
     * Setter for <code>public.qux.date_value</code>.
     */
    public void setDateValue(Date dateValue) {
        this.dateValue = dateValue;
    }

    /**
     * Getter for <code>public.qux.long_value</code>.
     */
    @Column(name = "long_value")
    public Long getLongValue() {
        return this.longValue;
    }

    /**
     * Setter for <code>public.qux.long_value</code>.
     */
    public void setLongValue(Long longValue) {
        this.longValue = longValue;
    }

    /**
     * Getter for <code>public.qux.currency_value</code>.
     */
    @Column(name = "currency_value")
    public Long getCurrencyValue() {
        return this.currencyValue;
    }

    /**
     * Setter for <code>public.qux.currency_value</code>.
     */
    public void setCurrencyValue(Long currencyValue) {
        this.currencyValue = currencyValue;
    }

    /**
     * Getter for <code>public.qux.byte_value</code>.
     */
    @Column(name = "byte_value")
    public Byte getByteValue() {
        return this.byteValue;
    }

    /**
     * Setter for <code>public.qux.byte_value</code>.
     */
    public void setByteValue(Byte byteValue) {
        this.byteValue = byteValue;
    }

    /**
     * Getter for <code>public.qux.big_decimal_value</code>.
     */
    @Column(name = "big_decimal_value", precision = 30, scale = 10)
    public BigDecimal getBigDecimalValue() {
        return this.bigDecimalValue;
    }

    /**
     * Setter for <code>public.qux.big_decimal_value</code>.
     */
    public void setBigDecimalValue(BigDecimal bigDecimalValue) {
        this.bigDecimalValue = bigDecimalValue;
    }

    /**
     * Getter for <code>public.qux.jsonb_value</code>.
     */
    @Column(name = "jsonb_value")
    public JSONB getJsonbValue() {
        return this.jsonbValue;
    }

    /**
     * Setter for <code>public.qux.jsonb_value</code>.
     */
    public void setJsonbValue(JSONB jsonbValue) {
        this.jsonbValue = jsonbValue;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Qux other = (Qux) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.bool == null) {
            if (other.bool != null)
                return false;
        }
        else if (!this.bool.equals(other.bool))
            return false;
        if (this.intValue == null) {
            if (other.intValue != null)
                return false;
        }
        else if (!this.intValue.equals(other.intValue))
            return false;
        if (this.doubleValue == null) {
            if (other.doubleValue != null)
                return false;
        }
        else if (!this.doubleValue.equals(other.doubleValue))
            return false;
        if (this.stringValue == null) {
            if (other.stringValue != null)
                return false;
        }
        else if (!this.stringValue.equals(other.stringValue))
            return false;
        if (this.timestampValue == null) {
            if (other.timestampValue != null)
                return false;
        }
        else if (!this.timestampValue.equals(other.timestampValue))
            return false;
        if (this.dateValue == null) {
            if (other.dateValue != null)
                return false;
        }
        else if (!this.dateValue.equals(other.dateValue))
            return false;
        if (this.longValue == null) {
            if (other.longValue != null)
                return false;
        }
        else if (!this.longValue.equals(other.longValue))
            return false;
        if (this.currencyValue == null) {
            if (other.currencyValue != null)
                return false;
        }
        else if (!this.currencyValue.equals(other.currencyValue))
            return false;
        if (this.byteValue == null) {
            if (other.byteValue != null)
                return false;
        }
        else if (!this.byteValue.equals(other.byteValue))
            return false;
        if (this.bigDecimalValue == null) {
            if (other.bigDecimalValue != null)
                return false;
        }
        else if (!this.bigDecimalValue.equals(other.bigDecimalValue))
            return false;
        if (this.jsonbValue == null) {
            if (other.jsonbValue != null)
                return false;
        }
        else if (!this.jsonbValue.equals(other.jsonbValue))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.bool == null) ? 0 : this.bool.hashCode());
        result = prime * result + ((this.intValue == null) ? 0 : this.intValue.hashCode());
        result = prime * result + ((this.doubleValue == null) ? 0 : this.doubleValue.hashCode());
        result = prime * result + ((this.stringValue == null) ? 0 : this.stringValue.hashCode());
        result = prime * result + ((this.timestampValue == null) ? 0 : this.timestampValue.hashCode());
        result = prime * result + ((this.dateValue == null) ? 0 : this.dateValue.hashCode());
        result = prime * result + ((this.longValue == null) ? 0 : this.longValue.hashCode());
        result = prime * result + ((this.currencyValue == null) ? 0 : this.currencyValue.hashCode());
        result = prime * result + ((this.byteValue == null) ? 0 : this.byteValue.hashCode());
        result = prime * result + ((this.bigDecimalValue == null) ? 0 : this.bigDecimalValue.hashCode());
        result = prime * result + ((this.jsonbValue == null) ? 0 : this.jsonbValue.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Qux (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(bool);
        sb.append(", ").append(intValue);
        sb.append(", ").append(doubleValue);
        sb.append(", ").append(stringValue);
        sb.append(", ").append(timestampValue);
        sb.append(", ").append(dateValue);
        sb.append(", ").append(longValue);
        sb.append(", ").append(currencyValue);
        sb.append(", ").append(byteValue);
        sb.append(", ").append(bigDecimalValue);
        sb.append(", ").append(jsonbValue);

        sb.append(")");
        return sb.toString();
    }
}
