package io.github.qlivedev.graphql;

import graphql.language.AstPrinter;
import graphql.language.AstSorter;
import graphql.language.Document;
import graphql.language.EnumTypeDefinition;
import graphql.language.EnumValueDefinition;
import graphql.language.FieldDefinition;
import graphql.language.InputObjectTypeDefinition;
import graphql.language.InputValueDefinition;
import graphql.language.Node;
import graphql.language.ObjectTypeDefinition;
import graphql.language.SDLDefinition;
import graphql.schema.GraphQLSchema;
import graphql.schema.idl.DirectiveInfo;
import graphql.schema.idl.SchemaParser;
import graphql.schema.idl.SchemaPrinter;
import graphql.schema.idl.TypeDefinitionRegistry;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

import static org.hamcrest.MatcherAssert.*;
import static org.hamcrest.Matchers.*;

/**
 * Keeps {@code execution-test-schema.graphql} equal to the union of {@link ExecutionTestDomains#all()}, the schema the
 * IDE GraphQL plugin checks the query strings in {@link QLiveDomainExecutionTest} against.
 * <p>
 * Object, input object and enum types of the same name merge their fields and values, so a query valid in its own
 * domain is valid in the union. The reverse does not hold: the union accepts a field a query's own domain lacks, which
 * the test then reports when it runs. A field or value present in several domains with different types fails the
 * merge, and so does any other type whose definitions differ. Descriptions come from the first domain that defines the type.
 * </p>
 * <p>
 * When the file is stale, the test rewrites it and fails, so the new schema shows up in the diff.
 * </p>
 */
public class ExecutionTestSchemaTest
{
    private final static Path SCHEMA_PATH = Path.of(
        "src/test/java/io/github/qlivedev/graphql/execution-test-schema.graphql"
    );


    @Test
    public void schemaFileIsCurrent() throws IOException
    {
        final String schema = "# Generated by ExecutionTestSchemaTest from ExecutionTestDomains. Do not edit.\n\n" +
            printUnion(ExecutionTestDomains.all());

        final String existing = Files.exists(SCHEMA_PATH) ?
            Files.readString(SCHEMA_PATH, StandardCharsets.UTF_8) : null;

        if (!schema.equals(existing))
        {
            Files.writeString(SCHEMA_PATH, schema, StandardCharsets.UTF_8);
        }

        assertThat(SCHEMA_PATH + " was stale and has been regenerated; review and commit it", existing, is(schema));
    }


    private static String printUnion(List<QLiveDomainBuilder> domains)
    {
        // The IDE knows the specified directives; repeating their definitions would only add noise.
        final SchemaPrinter printer = new SchemaPrinter(
            SchemaPrinter.Options.defaultOptions()
                .includeDirectiveDefinition(name -> !DirectiveInfo.isGraphqlSpecifiedDirective(name))
        );
        final Map<String, SDLDefinition<?>> merged = new LinkedHashMap<>();
        for (QLiveDomainBuilder domain : domains)
        {
            final GraphQLSchema schema = domain.buildGraphQLSchema();
            final TypeDefinitionRegistry registry = new SchemaParser().parse(printer.print(schema));

            registry.schemaDefinition().ifPresent(def -> merge(merged, "schema", def));
            registry.types().values().forEach(def -> merge(merged, def.getName(), def));
            registry.scalars().values().forEach(def -> merge(merged, def.getName(), def));
            registry.getDirectiveDefinitions().values().forEach(def -> merge(merged, "@" + def.getName(), def));
        }

        // Printed as merged rather than through a GraphQLSchema, whose validation rejects the null default values
        // QLive gives non-null input fields. The file shows what the domains serve, defaults included.
        final Document document = Document.newDocument().definitions(new ArrayList<>(merged.values())).build();
        return AstPrinter.printAst(new AstSorter().sort(document));
    }


    private static void merge(Map<String, SDLDefinition<?>> merged, String key, SDLDefinition<?> def)
    {
        final SDLDefinition<?> existing = merged.get(key);
        if (existing == null)
        {
            merged.put(key, def);
        }
        else if (existing instanceof ObjectTypeDefinition a && def instanceof ObjectTypeDefinition b)
        {
            final List<FieldDefinition> fields = mergeMembers(
                key, a.getFieldDefinitions(), b.getFieldDefinitions(), FieldDefinition::getName
            );
            merged.put(key, a.transform(builder -> builder.fieldDefinitions(fields)));
        }
        else if (existing instanceof InputObjectTypeDefinition a && def instanceof InputObjectTypeDefinition b)
        {
            final List<InputValueDefinition> fields = mergeMembers(
                key, a.getInputValueDefinitions(), b.getInputValueDefinitions(), InputValueDefinition::getName
            );
            merged.put(key, a.transform(builder -> builder.inputValueDefinitions(fields)));
        }
        else if (existing instanceof EnumTypeDefinition a && def instanceof EnumTypeDefinition b)
        {
            final List<EnumValueDefinition> values = mergeMembers(
                key, a.getEnumValueDefinitions(), b.getEnumValueDefinitions(), EnumValueDefinition::getName
            );
            merged.put(key, a.transform(builder -> builder.enumValueDefinitions(values)));
        }
        else if (!signature(existing).equals(signature(def)))
        {
            throw new IllegalStateException(
                "Cannot merge differing definitions of " + key + ":\n" +
                    AstPrinter.printAst(existing) + "\n" + AstPrinter.printAst(def)
            );
        }
    }


    private static <T extends Node<T>> List<T> mergeMembers(
        String typeName,
        List<T> existing,
        List<T> added,
        Function<T, String> nameOf
    )
    {
        final Map<String, T> members = existing.stream().collect(
            Collectors.toMap(nameOf, m -> m, (a, b) -> a, LinkedHashMap::new)
        );
        for (T member : added)
        {
            final T present = members.putIfAbsent(nameOf.apply(member), member);
            if (present != null && !signature(present).equals(signature(member)))
            {
                throw new IllegalStateException(
                    "Cannot merge " + typeName + "." + nameOf.apply(member) + ": " +
                        signature(present) + " vs " + signature(member)
                );
            }
        }
        return new ArrayList<>(members.values());
    }


    /**
     * The definition as SDL without string literals. That drops the descriptions, which domains may phrase differently
     * for the same type, and string default values along with them.
     */
    private static String signature(Node<?> node)
    {
        return AstPrinter.printAstCompact(node).replaceAll("\"\"\"(?s:.*?)\"\"\"|\"(?:[^\"\\\\]|\\\\.)*\"", "");
    }
}
